### ISSUE TITLE
Jenkins is not building plugin with plugin.yml or config.yml.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#1]
Missing resource folder to include files in compile?

**Comment by Rayzr522** [comment]
Hmmm I see that, I think I know what's going on......

**Comment by Rayzr522** [comment]
Ok fixed it. For some reason I believe @gvlfm78 moved the `plugin.yml` and `config.yml` out of the resources folder. I put them back, you can get the fixed version here:
https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/19/
