### ISSUE TITLE
Config for shield damage reduction

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#100]
* Allowing both percentages and half-heart values

**Comment by gvlfm78** [comment]
Added in test build [#137](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/137/)

**Comment by Kainzo** [comment]
I've had several users test this and it is blocking all incoming damage on a 1.11 server.

is there a method to allow a configuration instead of a set "half heart" value?
because Heroes doesnt translate hearts the same, players have 1K health and still 10 hearts, etc.

**Comment by gvlfm78** [comment]
Yes, that's exactly what's in the test build I linked you
