### ISSUE TITLE
Set every teams' collison to always 

### ISSUE THREAD

**Issue by RookieTEC9** [gvlfm78/BukkitOldCombatMechanics#101]
Please, check if a player is on a team and if that is true is set that team's collison to true rather than forcing than to the OCMinternal team. Only add them to the OCMinternal team if they are not on any team.

**Comment by gvlfm78** [comment]
IIRC in order for collisions between players to work the players need to be in the same team.

This, together with the fact that disabling the collisions in this way also made players unable to collide with animals and other objects (such as minecarts), and the fact that is conflicted with scoreboard and tablist plugins, is why I have substituted the teams system for collisions with packets in the [latest test builds](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/).
