### ISSUE TITLE
Armor bar not showing

### ISSUE THREAD

**Issue by Skizzles** [gvlfm78/BukkitOldCombatMechanics#103]
On 1.12 clients on my Server the Armor bar showing how much Armor protection you have does not show. This is for any armor.
Example of Armor:
![lrckduyfrreg8ojfwapqtg](https://user-images.githubusercontent.com/30563757/28750648-97789cc8-74a5-11e7-909e-2b932664a505.png)
Issue:
![ozt2ksgnt16x_l_ymxc0oq](https://user-images.githubusercontent.com/30563757/28750650-b3c2a05e-74a5-11e7-98b4-43ef68bab8a6.png)

**Comment by gvlfm78** [comment]
OCM is not supposed to touch the anything but the armour toughness value. That piece of armour is missing the Armour value. It is possible there is a conflict with whatever renamed it to "Immortal Chestplate"

**Comment by Skizzles** [comment]
I removed the latest version and rolled back and the Armor Bar came back. So something wrong with that latest version. Also the name is just Crate Reloaded. Which just sets the colors of the name. Why does it have 9999 armor toughness?

**Comment by gvlfm78** [comment]
* What is the exact version in question?
* How did you add the "Donor Armor" label to the armour? (Not the colour, the label itself)

It has 9999 toughness as part of one of the OCM modules in order to make the damage received with the armour like in 1.8.

**Comment by Skizzles** [comment]
The version that caused it to disappear is 1.5.1.
As for the Donor Label and the Color Label it's all add through Crate Reloaded using the ability to rename items and add special lore to them.

**Comment by gvlfm78** [comment]
Could you try the [latest test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/) and see if you still have the issue? Try taking the armour piece off and putting it back on, while in survival mode, without shift-clicking, and report what happens to each of the two tags (armour & toughness)
