### ISSUE TITLE
Shield damage reduction for all shields

### ISSUE THREAD

**Issue by pvprangergod** [gvlfm78/BukkitOldCombatMechanics#104]
Hi
I want the 50% damage reduction to work with craftable shields instead of sword-blocking.
Also could the damage reduction be altered for arrows and melee, for example, it would be nice to have arrows do 50% less damage and melee only 33% while blocking.

**Comment by gvlfm78** [comment]
So you would like to:
* be able to edit the shield damage reduction separately from the sword blocking module
* be able to edit the projectile damage reduction separately from the melee damage reduction

**Comment by pvprangergod** [comment]
Yes, because I want shields to still be crafted as vanilla but nerfed

**Comment by jamesol1** [comment]
I know this isn't my post. So feel free to remove this comment. But i like this idea a lot and thought of something similar myself. To expand on it... would it be possible for the % of reduced damage to be adjusted by the config? So for instance damage reduction: 0.50 (as the default option)... but players can change it to 0.85.. 0.20... etc.

**Comment by gvlfm78** [comment]
The config should already contain a shield damage reduction setting...

**Comment by jamesol1** [comment]
That seems to be only under the sword blocking section though. I have that disabled. I have hand switching disabled BUT shields on the whitelist so players can hold them in the standard 1.9 way and block etc.

**Comment by gvlfm78** [comment]
What exactly do you mean by "which doesn't require players to have the shield item and the ''shield'' of course doesn't ever break."?

**Comment by jamesol1** [comment]
The normal 1.9 shield when used has a limited amount of uses. I guess the whole point of sword blocking isn't to implement shields but to try and resemble the sword blocking mechanic of which can't be done without using a shield? What I'm wondering is if the same %damage reduction could be used for shields. I like 1.8 spam clicking combat but with shields. BUT having a shield that doesn't absorb 100% damage would allow players who just hold it down in pvp and around mobs to still be punished by taking some damage.

**Comment by gvlfm78** [comment]
Transferred to #113
