### ISSUE TITLE
Crafting blacklist & unbreakable anvil

### ISSUE THREAD

**Issue by Terrifical** [gvlfm78/BukkitOldCombatMechanics#106]
unbreakable anvil (give command)

make anything non-craftable

**Comment by Rayzr522** [comment]
I don't know @gvlfm78's opinion on idea 1, but making anything unctaftable is not the job of OCM. It does not it in any way. gvlfm gets the finally say in all of this, of course, but I really feel the idea 2 has nothing to do with the goals of OCM.

**Comment by Terrifical** [comment]
@rayzr522 I just thought that since there is an option to disable shield crafting why not add a black list crafting section.

I thought of another feature, what about /ping command?  I think that would go great with this plugin. Since a players ping is important aspect when is comes to pvp

/ping <player>

**Comment by Rayzr522** [comment]
The ability to disable crafting of shields is so you can simulate older versions which didn't have shields, it doesn't make sense in other cases. 

As for /ping, even though it's important for combat, it's still not the place of the plugin responsible for managing game mechanics to provide general-use commands.

**Comment by gvlfm78** [comment]
I thought I had already added the ability to disable crafting for any item so that if someone wants to disable any new items that get introduced that they believe will affect pvp they can. 

I am not sure this is the correct plugin for unbreakable anvils.
