### ISSUE TITLE
Require shield item to use it (by right clicking) 

### ISSUE THREAD

**Issue by jamesol1** [gvlfm78/BukkitOldCombatMechanics#108]
There is currently an option for players to right click to active a shield. I really like this it means players dont have to use the multiple hand switching 1.9 feature etc. BUT could you add a way of requiring players to have a shield equipped or at least on them in order for them to use a shield.

Thanks, apart from that... amazing plugin!

**Comment by gvlfm78** [comment]
I'm not sure what you mean, have you tried changing the config to meet your needs?

**Comment by jamesol1** [comment]
Yes I did. I thought that was a given. I guess i should post my config so you can see the other relevant options.
https://pastebin.com/JPQ56Hwj
Thanks!
I'd like to be able to not have to deal with the switching items slot but also be able to use the shield... which i can using your plugin... but it doesn't require me to have a shield which makes it from a roleplay/survival sense weird.

**Comment by jamesol1** [comment]
Ok i found a way just now! The whitelist option under the title for switching your hand... i didn't know you could disable it but allow it for certain items. Great.
