### ISSUE TITLE
Shield damage reduction when sword-blocking module disabled

### ISSUE THREAD

**Issue by jamesol1** [gvlfm78/BukkitOldCombatMechanics#113]
I commented this on another post... I thought it would be best for me to make an official post about it. I'm hoping it should be very easy to add in considering it is enabled for sword blocking.

so... there seems to be only one way of configurating the amount a shield blocks damage wise which is through 'sword blocking'. I have that disabled meaning shields block 100% damage (of which I'm hoping to adjust). I have hand switching disabled BUT with shields on the white-list so players can hold them in the standard 1.9 way and block etc (requiring the item and making them have to actually hold the shield not just swipe it out).

Right now the % shield blocking feature only works under sword blocking. 

Thanks for reading.

**Comment by gvlfm78** [comment]
Summary:

- Allow the shield damage reduction component of the sword-blocking module to be enabled independently
- Allow changing the projectile damage reduction separately from the melee damage reduction

**Comment by gvlfm78** [comment]
Added with commits https://github.com/gvlfm78/BukkitOldCombatMechanics/commit/08b82b25f2d0bcd5f35098e40d249e88b1bfb703 https://github.com/gvlfm78/BukkitOldCombatMechanics/commit/755f773f56aee2ccbcbfcb1cb15d908082d37548 https://github.com/gvlfm78/BukkitOldCombatMechanics/commit/40494f9764964005c182732f1cfd33097a96a1c0
