### ISSUE TITLE
Old Minecraft PvP Sounds.

### ISSUE THREAD

**Issue by FrenzyCake** [gvlfm78/BukkitOldCombatMechanics#115]
Change 1.9+ sounds back to 1.7/1.8 sounds, they were much smoother and overall better.
By old sounds I mean old hitting sounds, bow pulling sounds and overall all PvP based sounds.

**Comment by gvlfm78** [comment]
I don't think there's a way to play custom sounds using a plugin without the use of a resource pack and some sorcery, if you find a way please tell us and we will reopen this issue.
