### ISSUE TITLE
Fishing rod pulling.

### ISSUE THREAD

**Issue by FrenzyCake** [gvlfm78/BukkitOldCombatMechanics#116]
Remove fishing rod pulling and just leave fishing rod knock-back, fishing rod pulling is a new feature in 1.9+ version which a lot of people don't like, and there's currently no plugin on spigot which entirely disables it, so I think that would be pretty cool to see in this plugin features.
By fishing rod pulling I mean a "thing" added in 1.9+ Minecraft versions where when you use fishing rod on a player you pull him closer to yourself. This was not a thing back in Minecraft 1.7/1.8. In Minecraft 1.7/1.8 when you used fishing rod on a player you would pull him further away from you not closer.
Here is a video example: https://www.youtube.com/watch?v=s7t46VEACIY

**Comment by gvlfm78** [comment]
I have added this in OCM version 1.6.2
