### ISSUE TITLE
Disable Crafting Issue

### ISSUE THREAD

**Issue by KfwPlayz** [gvlfm78/BukkitOldCombatMechanics#119]
I don't know if I'm doing it wrong or I formatted it wrong but when I try to add a block or item to the list, it does not work it only blocks the default item there (the shield) even with the added items. I format it like this:

disable-crafting:
  Disable the crafting of specified items
  enabled: true
  worlds: ["Factions"]
   List of denied items
  denied: [shield,hopper,golden_apple:1]  

(Do I need quotation marks or something like this "[item]" or this '[item]'?

**Comment by KfwPlayz** [comment]
Bump?

**Comment by gvlfm78** [comment]
You should not have quotation marks around "Factions"
