### ISSUE TITLE
Outdated server version

### ISSUE THREAD

**Issue by zr120cat** [gvlfm78/BukkitOldCombatMechanics#12]
http://pastebin.com/5PZmK27R This is the link for the error. Ive also tried another plugin and it did the same error. Im sure this is a dumb mistake so please help me

**Comment by gvlfm78** [comment]
Is your server up to date? It says the version is 1.9 in that log but it's as if it weren't up to date because it doesn't recognise the new event.

**Comment by zr120cat** [comment]
how would I check/fix this

**Comment by gvlfm78** [comment]
Do /version and you should get the exact bukkit version

**Comment by zr120cat** [comment]
okay thanks for fast reply! The version is 1.9-R0.1-SNAPSHOT

**Comment by gvlfm78** [comment]
Ok - do you have any reason to stick with 1.9 or can you update to 1.10?
Anyway, I have attached here both 1.9.4 and 1.10 that I just got using BuildTools provided by the Spigot team. You should try updating to one of these (obviously unzip them first and then replace the jar with the one you are using to run the server, and make a backup of the old file).

[spigot-1.10.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/478301/spigot-1.10.zip)
[spigot-1.9.4.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/478302/spigot-1.9.4.zip)

**Comment by zr120cat** [comment]
I would like to stick with 1.9 with some plugins that work. But ill think about switching. The main reason why im doing this is so I can use via version and this plugin combined. It would make it great like 1.8

**Comment by gvlfm78** [comment]
You _can_ stay with 1.9, just update from 1.9 to 1.9.4 and see if the problem is still there

**Comment by zr120cat** [comment]
ok

**Comment by zr120cat** [comment]
on my test server it worked, the slash feature is still in though but I think thats a bug. Ill download the plugins to the test server and see if they all work!

**Comment by gvlfm78** [comment]
Does it work?
