### ISSUE TITLE
Players Regen really fast

### ISSUE THREAD

**Issue by Snickerzzz** [gvlfm78/BukkitOldCombatMechanics#121]
Hi,
I am having an issue when players hit someone they regen their hearts super fast. I tried looking around but couldn't really find anything. 

Config: https://pastebin.com/FacCvRmk

**Comment by gvlfm78** [comment]
Does it happen _everytime_ somebody hits someone? Are there any exception?

**Comment by Snickerzzz** [comment]
I found out what the problem was. It was on my side I had the server in peaceful mode. Sorry
