### ISSUE TITLE
[Important!] Restore back to normal?!

### ISSUE THREAD

**Issue by ThanosDclxvi** [gvlfm78/BukkitOldCombatMechanics#123]
Hello, I uninstalled it but things didnt go all normal! For example the sword recharge bar isnt even there! How to restore back to normal? Thank you!

**Comment by gvlfm78** [comment]
What did you do exactly to _uninstall_ it?

**Comment by ThanosDclxvi** [comment]
I just deleted the jar file and it's folder, plus I deleted protocol lib

**Comment by gvlfm78** [comment]
Did you turn the server off first?

**Comment by ThanosDclxvi** [comment]
I did restart it, I don't think that I stopped it first

**Comment by gvlfm78** [comment]
You should have stopped the server, taken the plugin out and started it again.

Anyway, to fix your problem now, please follow the [instructions to use OCMFixer](https://github.com/Rayzr522/OCMFixer), created by Rayzr to fix players' attack cooldowns when OCM is not uninstalled correctly.

**Comment by ThanosDclxvi** [comment]
Does this fixer restore the economy data too?

**Comment by gvlfm78** [comment]
OCM has nothing to do with economy....

**Comment by Rayzr522** [comment]
If you have economy data that got wiped, then that's the fault of some other plugin. OCM doesn't interact with any economy plugins or their files.
