### ISSUE TITLE
Shield kept in inventory with keepInventory true

### ISSUE THREAD

**Issue by Blatower21** [gvlfm78/BukkitOldCombatMechanics#124]
If you have a pvp world with keepinventory true when the player dies he gets a normal shield beacause of the sword-blocking shield!
-Spigot 1.12
-OCM 1.6.1

**Comment by Rayzr522** [comment]
Wow, I can't believe this bug has gone unpatched for so long! It's now been fixed. Until this latest version gets released, here's a JAR with the patch:

[OldCombatMechanics-keepInventory-patch.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/1905373/OldCombatMechanics-keepInventory-patch.zip)
(Just unzip this, GitHub doesn't support uploading JAR files directly)

**Comment by HairyDragonBeck** [comment]
Rayzr is gey
