### ISSUE TITLE
Napple recipe is not removed upon reloading OCM

### ISSUE THREAD

**Issue by Turn3r** [gvlfm78/BukkitOldCombatMechanics#125]
Disabling old-golden-apples wont disable them. Setting the recipe to false still has them craftable for me and the potion effects effects setting stay whether I enable to disable that setting.

Also I enabled debug to see if it was saying anything and it said stuff about WeaponDamages and ArmourValues loading the values. I have those settings to false so I also wanted to make sure they aren't enabled.

Spigot 1.12.1 - git-Spigot-65e8124-bde2a93 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
Version of OCM plugin - 1.6.1

Config - https://pastebin.com/u9yQpJ0U
Console debug msg - https://pastebin.com/g90MF6ne (No console errors)

**Comment by gvlfm78** [comment]
* For your first issue, you haven't even enabled the module. You need to set **enabled:** to true.
* For the second issue, as it does not appear to be directly related to this one, I have opened a new issue [here](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/126) for it and will be looking at it separately.

**Comment by Turn3r** [comment]
I know the module isn't enabled. I don't want then to be craftable by the golden blocks but they are even though it is set to false. If I don't enable the module shouldn't mean that they shouldn't be craftable? If Im reading this wrong please let me know. Basically the module is disabled but it still lets the gapples with golden blocks be craftable and still gives them the old potion effects.

**Comment by gvlfm78** [comment]
So I've been looking for a while and have done some extensive testing and found out that in 1.12 you cannot remove a recipe once added without reloading the server. So I've made some changes to the way OCM adds the napple recipe, but if you disable the module and do `/ocm reload` you will have to reload the server to actually have the napple recipe stop working.

You can get the latest test build with these changes [here](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/).

**Comment by Turn3r** [comment]
Ok, I will grab the test build and try it out. Thanks for the help over the last few days!

**Comment by gvlfm78** [comment]
Closing this issue as there doesn't seem to be a fix for now except reloading the server.

**Comment by Rayzr522** [comment]
[I found a solution ;)](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#reload--)
