### ISSUE TITLE
Weapon damages are loaded even if the module is disabled

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#126]

**Comment by gvlfm78** [comment]
Should now be fixed in [latest test build](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/). @Turn3r

**Comment by Turn3r** [comment]
Thank you @gvlfm78 I will grab it!

**Comment by gvlfm78** [comment]
That is normal, it is just the plugin check that you have the correct value (either 1.9 default or what's specified in the config). Instead, I found I got an internal error when reloading, which I have now fixed in the [latest test version](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/).

**Comment by Turn3r** [comment]
Ok, thanks for clarifying!
