### ISSUE TITLE
Players getting different damage depending on client version

### ISSUE THREAD

**Issue by GlobooX** [gvlfm78/BukkitOldCombatMechanics#128]
Hi, i have some problems.. Players on my server reported some bugs

Player with 1.7.10 damaged victim 2 Hearts per hit
Player with 1.9+ damaged victim 1 Hearts per hit (Player must wait 1-2 second before next attack) <- If player spamming attack damage is 0 hearts ;/ Something like plugins does not work ;/

I have bug with colission too: sometimes player colission is working and sometimes not...

Spigot: 1.10.2-R0.1-SNAPSHOT
OldCombatMechanics: v1.6.1
Config: https://pastebin.com/nQHR6mrh

Sorry for my english ;/

**Comment by gvlfm78** [comment]
For your first issue, do you mean that players running 1.7.10 Minecraft _receive_ 2 hearts per hit or _inflict_ 2 hearts per hit?

For your second issue regarding collisions please open a different ticket and provide more detail.

Thank you for your collaboration.

**Comment by GlobooX** [comment]
Hi, victim is receive 2 hearts per hit on 1.7.10 and different value hearts on other versions.

**Comment by gvlfm78** [comment]
Is the victim on 1.7.10?

**Comment by GlobooX** [comment]
Victim is on 1.7 and Attacker is 1.10 = Attacker damage Victim with 1 hearts per hit
Victim is on 1.10 and Attacker is 1.7 = Attacker damage Victim with 3.5 hearts per hit

**Comment by GlobooX** [comment]
@ref

**Comment by gvlfm78** [comment]
Can you try turning on the **debug** mode (at the bottom of the config.yml) and reading the exact data given by the debug messages during an attack?

**Comment by GlobooX** [comment]
Hi, sorry for this report.. I found cause this error.. 
I have to just delete data file from worldName/playerdata/213-3213-13221ad.dat then averythink is ok..
I dont know why some players is bugged becouse .dat ;/

sorry for my english.

**Comment by gvlfm78** [comment]
That is strange... It is possible some other plugin messed with it. If you have this problem again we can reopen this issue and investigate further.
