### ISSUE TITLE
Console Error When The Shield In The 2nd Hand

### ISSUE THREAD

**Issue by NelsonHD** [gvlfm78/BukkitOldCombatMechanics#129]
Spigot Version :                   1.12.2-R0.1-SNAPSHOT
OCM Version:                      1.6.1
Copy of my config.yml :      https://pastebin.com/yDGGyrgk
Copy of full console error : https://pastebin.com/zt69Tikx

**Comment by gvlfm78** [comment]
Thank you for the detailed report. Please try the [latest test build](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/) and post any error you get while using that version.

Also, are there any specific actions that cause the error to appear?

**Comment by NelsonHD** [comment]
Spigot Version : 1.12.2-R0.1-SNAPSHOT
OCM Version: 1.6.2
Copy of my config.yml : https://pastebin.com/yDGGyrgk
Copy of full console error : https://pastebin.com/H4K1bLZi

When i want to put the shield on the 2nd hand slow, then it show this error.

**Comment by NelsonHD** [comment]
Spigot Version : 1.12.2-R0.1-SNAPSHOT
OCM Version: 1.6.2
Copy of my config.yml : https://pastebin.com/yDGGyrgk
Copy of full console error : https://pastebin.com/tG37Rh9V

Cant /ocm reload

**Comment by gvlfm78** [comment]
The recipe error should now be fixed in the [latest test version](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/). I'm now looking into the original error.

**Comment by gvlfm78** [comment]
Ok now the original error should be fixed too. Please try the [latest test version](https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/) and report any further errors.

**Comment by NelsonHD** [comment]
OK. It seem like no error now. THX
