### ISSUE TITLE
Will not regenerate health past 20 hearts 

### ISSUE THREAD

**Issue by DankPotion** [gvlfm78/BukkitOldCombatMechanics#13]
As the title says, if I /effect DankPotion_ minecraft:healthboost 60 5, it will not regenerate the empty hearts. It knocks people back down to 20 hearts if they do somehow regenerate past 20 hearts. 

Here's a little video showing the bug. (Watch Please.)
https://youtu.be/XxgWWma29CY

**Comment by gvlfm78** [comment]
Try with the attached test build (unzip it first)
[OldCombatMechanics.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/491245/OldCombatMechanics.zip)
