### ISSUE TITLE
Invulnerability when rodding someone.

### ISSUE THREAD

**Issue by LinsaFTW** [gvlfm78/BukkitOldCombatMechanics#136]
Version of Bukkit/Spigot: 1.12.2 Paperspigot

Version of OCM plugin: 1.6.2

The config is the default one.

No console errors.

Just after rodding someone you cant hit him for 3 seconds.

**Comment by gvlfm78** [comment]
Does this also happen with version 1.6.1?

**Comment by LinsaFTW** [comment]
Yes :(

**Comment by LinsaFTW** [comment]
https://hastebin.com/fisawowayo.vbs Maybe this has something to do? i checked console and i have this error

**Comment by LinsaFTW** [comment]
Yeah , its a incompatibility with essentials teleport-invulnerability: 5

I patched it by setting teleport-invulnerability: 0 but it would be better if you make it compatible :) Thanks.

**Comment by gvlfm78** [comment]
Between version 1.6.1 and 1.6.2 I changed some bits of how the rodding works. Does the error also appear when using 1.6.2?

**Comment by gvlfm78** [comment]
Also, isn't essentials no longer maintained, and essentialsX is the fork that still is?

**Comment by LinsaFTW** [comment]
The error appears on 1.6.2 and 1.6.1 , im using EssentialsX.

**Comment by gvlfm78** [comment]
I'm not sure about the relation between that error and OCM, as OCM is never mentioned in the error. Is that the only error that ever appears?

Also, have you tried updating EssentialsX to the [latest version](https://ci.lucko.me/job/Essentials/)?

**Comment by LinsaFTW** [comment]
Yes im using the latest version.

In the essentials site says that teleport-invulnerability makes players invulnerable after teleporting , maybe ocm is using any sort of teleportation to make the rod work? I dont know xD

**Comment by LinsaFTW** [comment]
Nvm i updated essentialsx and it got fixed! thanks :D

**Comment by gvlfm78** [comment]
Yes, the player gets teleported by a small amount backwards when they get hit by the bobber. But Essentials shouldn't be interfering as OCM should have the last say on the event in order to avoid problems like this.
