### ISSUE TITLE
Old Knockback feature

### ISSUE THREAD

**Issue by LinsaFTW** [gvlfm78/BukkitOldCombatMechanics#137]
In 1.12.2 The Knockback is too low , it would be a good feature to make knockback like the 1.8 one that makes players knockback further away.

**Comment by ItzVinex** [comment]
Any idea when this is going to be added?

Nov 8, 2017 | July 27, 2018

**Comment by Rayzr522** [comment]
It would be great to see a chart describing how the knockback was before and then after the combat update. It would be nearly impossible to implement this without it.

**Comment by LinsaFTW** [comment]
Cant you test it by yourself? Im not a expert to tell what changed. I just feel it changed and its not ideal for combos.

I really recommend you getting into 1.7/1.8 gameplay and 1.9 gameplay so you can tell the difference, ive already managed to make custom knockback config that is like 1.7 kb.

**Comment by I-Al-Istannen** [comment]
@LinsaFTW Can you try the build I linked [here](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/203#issuecomment-408690422) and see if the *fishing rod* knockback is what you want all knockback to be? You need to enable `old fishing knockback` in the config
