### ISSUE TITLE
Fishing rod cumulative knockback

### ISSUE THREAD

**Issue by LinsaFTW** [gvlfm78/BukkitOldCombatMechanics#139]
Version of Bukkit/Spigot: 1.12.2 Paperspigot

Version of OCM plugin: 1.6.2

Default config.

No console errors.

The fishing rod doesnt have Hit Delay and that means players can spam the rod to make other players fly or even get bugged by the Anti-Cheat.

I think you should add a 20 ticks hitdelay to the rod damage so players dont spam it.

**Comment by gvlfm78** [comment]
@LinsaFTW Sorry for having forgotten about this issue but I have now added a configurable fishing rod knockback hit delay if you wish to try it.

**Comment by Rayzr522** [comment]
Please test out [the latest development build](http://ci.rayzr.tech/job/OldCombatMechanics/) and let us know if this solves your issue.
