### ISSUE TITLE
Weird messages on console when i login

### ISSUE THREAD

**Issue by NoChanceSD** [gvlfm78/BukkitOldCombatMechanics#14]
It seems when i login the plugin always prints the following to console:

> Oy vey
> rglkieruigr: null null

Maybe it is some debug code you forgot?

**Comment by Rayzr522** [comment]
I found one of them in the Spigot update listener... now I have to find the other one 😛

**Comment by gvlfm78** [comment]
Whoops... Sorry for that, it was just gibberish I was using as debug code to test a feature. I'll pay more attention to it in future.

**Comment by Rayzr522** [comment]
I removed it :wink:
