### ISSUE TITLE
Re-enable 1.12.2 mechanics

### ISSUE THREAD

**Issue by Artlie22** [gvlfm78/BukkitOldCombatMechanics#140]
i cant re-enable 1.12.2 mechanics..
i have un-installed this plugin and i cant remove attack speed

(Sorry for bad English)

**Comment by gvlfm78** [comment]
What way did you "uninstall" the plugin

**Comment by Artlie22** [comment]
i have removed the plugin from plugins folder and attack speed not changed..

**Comment by Rayzr522** [comment]
What version of the plugin we’re you using?

**Comment by Artlie22** [comment]
1.6.2

**Comment by gvlfm78** [comment]
What did you do to 'uninstall' the plugin?
