### ISSUE TITLE
Cannot cast Double to Integer

### ISSUE THREAD

**Issue by huynhqtienvtag** [gvlfm78/BukkitOldCombatMechanics#142]
Plugin Version: 1.6.2
Spigot Version: Paper 1.11.2 (with ViaVersion, ViaBackward and ProtocolSupport)
Log: https://pastebin.com/nwd2ubPT
Config: https://pastebin.com/0s2vTxYf

**Comment by gvlfm78** [comment]
Are you wearing any items with custom NBT tags on them?

**Comment by huynhqtienvtag** [comment]
Yes, with Health Attribute

**Comment by gvlfm78** [comment]
Were the NBT tags added by a plugin or with a command?

**Comment by huynhqtienvtag** [comment]
by a plugin, I used Myitems

**Comment by gvlfm78** [comment]
Are you giving any command/order to tell that plugin how to make the item?
