### ISSUE TITLE
Brewing Stand

### ISSUE THREAD

**Issue by LinsaFTW** [gvlfm78/BukkitOldCombatMechanics#143]
Version of Bukkit/Spigot: 1.12.2 Paperspigot

Version of OCM plugin: 1.6.2

Default config.

No console errors.

The brewing stands doesnt refuel even with the world added to the list.

![2017-11-12_20 39 04](https://user-images.githubusercontent.com/25271111/32704772-898a086c-c7e9-11e7-9069-d480bf36ac21.png)

Hope you can fix this soon :c all my 1.7 - 1.8 players cant make potions because of this.

**Comment by gvlfm78** [comment]
Did it used to work before?

**Comment by LinsaFTW** [comment]
No , never.

**Comment by gvlfm78** [comment]
If you disable the old brewing stand module in the config does it work?

**Comment by LinsaFTW** [comment]
No...

**Comment by Rayzr522** [comment]
If the old brewing stand module is disabled, then it's not the fault of OCM, right @gvlfm78?

**Comment by gvlfm78** [comment]
If the old brewing stand module is disabled, I don't see how any other module would affect this...

The ultimate test, just to be sure would be to disable OCM entirely and see if the issue still persists

**Comment by LinsaFTW** [comment]
It persists... what should i do? I want the old brewing stand :(

Btw Infinite lapis Enchantment table works ok.

**Comment by gvlfm78** [comment]
If disabling OCM doesn't make it work it means some other plugin is causing this...

You need to go through the list of plugins you have installed and look at which ones could possibly affect brewing stands, then disable each and check if brewing stand work

**Comment by LinsaFTW** [comment]
OCM Old Brewing Stand doesnt work even without any extra plugins installed...

Im using Paperspigot 1.12 w/ProtocolSupport

**Comment by gvlfm78** [comment]
What do you mean "OCM Old Brewing Stand doesnt work even without any extra plugins installed..."

as I said above, you need to first:

1. Disable the module and see if brewing stands work normally
2. Disable OCM and see if brewing stands work normally

I have no idea what you just did...

**Comment by LinsaFTW** [comment]
Dude...

I tried the following things:

1. Removed all the plugins and only letting OCM installed with OBS config enabled. Still 1.9.

2. Brewing Stands are 1.9 even if the module is disabled or enabled with and without plugins.

3. Reinstalling the plugin doesnt fix the issue.

What else do you want me to try? -.-

**Comment by gvlfm78** [comment]
So your problem is that 1.7 and 1.8 players cannot brew potions because it doesn't "refuel".
Unless your problem is "Brewing Stands are 1.9" regardless of the state of the module.
These are two completely different issues. What is your exact issue?

**Comment by LinsaFTW** [comment]
The brewing stand is 1.9 means it isnt refuelling.

**Comment by gvlfm78** [comment]
and what is the behaviour for a 1.7/1.8 client?

**Comment by LinsaFTW** [comment]
They want to brew the potions and the fire powder doesnt refuell. This happens on 1.12 aswell.

**Comment by gvlfm78** [comment]
but there is no "refuelling" behaviour in before 1.9, isn't there?

**Comment by LinsaFTW** [comment]
In 1.8 brewing stands doesnt need fuel.

**Comment by gvlfm78** [comment]
So can 1.7 and 1.8 people use brewing stands or not?

**Comment by LinsaFTW** [comment]
Dude can you be more clear with your answers? The refuelling doesnt work on 1.8 or 1.9....

**Comment by gvlfm78** [comment]
I was going to ask _you_ to be more clear with your answers because I properly don't understand what's working and what's not...

Also stop asking to 'fix it'; that's exactly what we're doing right now. I can't just press a couple buttons and make everything magically work, the first step is to know exactly _what_ is not working.

**Comment by LinsaFTW** [comment]
Im being really clear. No firepowder appears on the fuel slot. Thats all. Did you understand my answer? Do i have to be more specific?

No firepowder is appearing on the fuel slot when i have this option activated.

More specific?

When having the OLD BREWING STAND option activated on spigot 1.12 on all the clients (1.7 - 1.12) the firepowder doesnt regenerate on the fuel slot of the brewingstand.

**Comment by gvlfm78** [comment]
**BUT**, in 1.7 and 1.8, there was no such thing as refuelling a brewing stand. So how is it not being added/not working in those versions?

**Comment by LinsaFTW** [comment]
Because the server is 1.12. The 1.8 - 1.7 players cant see the fuel slot so if it doesnt refuel they cant craft potions because they cant place fuel. Thats why i want a fast fix :(

**Comment by Rayzr522** [comment]
The fuel slot is server-side. Whether or not clients see it is irrelevant. If the fuel is present server-side, then the potions should brew. Are 1.9+ players getting the blaze powder automatically added to their brewing stands via OCM?

**Comment by gvlfm78** [comment]
I believe I changed the way that worked some time ago to automatically set the fuel level instead of adding blaze powder, in order to avoid item duplication issues

**Comment by Rayzr522** [comment]
Either way, are 1.9+ having their brewing stands fueled by OCM? If so, then it would still work for 1.7 and 1.8 players, as the fuel level of a brewing stand is entirely client-side.

**Comment by LinsaFTW** [comment]
Why dont you understand what i say ;-; I said it doesnt work on 1.12 - 1.7 clients...

**Comment by Rayzr522** [comment]
Ah, okay. With the default OCM config, you said?

**Comment by LinsaFTW** [comment]
I tried my config and the default.

**Comment by Rayzr522** [comment]
Could you [upload your config](https://hastebin.com) so I can see what your options are?

**Comment by LinsaFTW** [comment]
https://hastebin.com/vibidadipa.bash

**Comment by Rayzr522** [comment]
Hmm, true, with default config (`old-brewing-stand` enabled), I had to manually fuel the brewing stand with blaze powder. Bug confirmed, @gvlfm78.

**Comment by gvlfm78** [comment]
Is this something that broke with 1.12?

**Comment by Rayzr522** [comment]
Quite possibly. I have other things to work on, but I have a small theory as to why this isn't working. I'll keep you posted :)

**Comment by Rayzr522** [comment]
#144 -- there ya go!

**Comment by gvlfm78** [comment]
Ok I have finally managed to get the Jenkins server back up. @LinsaFTW can you try the [latest OCM test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/) and check if it now works as intended?

**Comment by LinsaFTW** [comment]
Works good :D thanks! Fixed!
