### ISSUE TITLE
Inconsistent Damage rates

### ISSUE THREAD

**Issue by zeronerve** [gvlfm78/BukkitOldCombatMechanics#146]
I have some players who, despite having consistent health, armor, and weapons as other players, take damage much slower than others. One player requires only 4 or 5 hits to kill with a stone sword, and other players take 20-25 hits with the same kit. Any ideas?

Here's a pastebin on my config:
server.platform: bukkit
server.plugins: 
 - CleanroomGenerator: 1.0.0
 - Essentials: TeamCity
 - ChatControl: 5.6.1
 - Modifyworld: 1.20-SNAPSHOT
 - Votifier: 2.3.5
 - ProtocolLib: 4.3.0
 - OldCombatMechanics: 1.6.2
 - VotingPlugin: 5.12
 - FastAsyncWorldEdit: 17.12.26-994856b-952-18.0.9
 - EssentialsChat: TeamCity
 - PermissionsEx: 1.23.4
 - PartyAndFriendsGUI: 1.0.158-E
 - Vault: 1.6.1
 - ProtocolSupport: 4.29-dev
 - FastAsyncVoxelSniper: 17.12.26-994856b-952-18.0.9
 - Statscraft: 1.1.0
 - Citizens: 2.0.22-SNAPSHOT (build 1493)
 - CaptureTheFlag: 2.1.2
 - ServerSigns: 4.5.1
 - WorldEdit: 6.1.7;dd00bb1
 - PlotSquared: 17.12.09-59557cf-1945
 - Multiverse-Core: 2.5-b719
 - WorldGuard: 6.2.1;84bc322
 - DiscordSRV: 15.4
 - Multiverse-NetherPortals: 2.4-b530
 - Multiverse-Portals: 2.5.0-b751
 - ArmorStandTools: 2.4.3
 - HolographicDisplays: 2.2.6
 - TouchscreenHolograms: 1.3.2
 - VoxelSniper: 5.171.0-SNAPSHOT
server.version: git-Paper-1286 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT

memory.free: 2453788048
memory.max: 3665821696
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_151'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '4.9.68-x86_64-linode89'

**Comment by zeronerve** [comment]
Just ran a test with two players. I had /ocm toggle enabled per player so that i could see if the toggle affected damage rates. One player took 8-10 hits to kill, the other took 4 (using the same sword and no armor). I toggled ocm for each player and nothing changed.

**Comment by gvlfm78** [comment]
Enable the **debug** setting in the config.yml and see what the debug messages regarding the damage inflicted read

**Comment by zeronerve** [comment]
![debug](https://user-images.githubusercontent.com/34899120/34416074-65791084-ebb7-11e7-9196-2088e035ff37.jpg)

Thanks for the reply. Same debug results for both players.

**Comment by gvlfm78** [comment]
Do the players hit get any debug messages?

**Comment by zeronerve** [comment]
![2017-12-28_12 17 19](https://user-images.githubusercontent.com/34899120/34419392-3e39792a-ebc9-11e7-9c66-ae86fc160376.png)

The player receiving the hit sees these debug messages.

**Comment by zeronerve** [comment]
So I removed all plugins except Multiverse, Permissions, and ProtocolSupport. Then ran some tests. 
-----------------------------------------------------------------------------------
Killer's debug with cooldown enabled...a 19 or 20-hit kill (fast clicking) with diamond sword and no armor. 
![killer-cooldown-enabled](https://user-images.githubusercontent.com/34899120/34421633-20712afc-ebd6-11e7-92a5-24d605adacd6.png)
-----------------------------------------------------------------------------------
Deadguy's debug with cooldown enabled.
![deadguy cooldown-enabled](https://user-images.githubusercontent.com/34899120/34421636-20ada6a8-ebd6-11e7-908f-daf1849a7ec7.png)
-----------------------------------------------------------------------------------
Killer's debug with cooldown DISABLED...a 6- or 7-hit kill with diamond sword and no armor. 
![killer-cooldown-disabled](https://user-images.githubusercontent.com/34899120/34421635-20988836-ebd6-11e7-9fdf-424245ca0f7e.png)
-----------------------------------------------------------------------------------
Deadguy's debug with cooldown DISABLED.
![deadguy-cooldown-disabled](https://user-images.githubusercontent.com/34899120/34421634-2084b63a-ebd6-11e7-9423-78302a3b89be.png)
-----------------------------------------------------------------------------------

Looks like I might have a plugin conflict which is affecting cooldowns/damage rates.  I'm going to start enabling some of the likely supects one by one, but if you have ideas, please let me know. The full plugin list is in my first post. Thanks!

**Comment by zeronerve** [comment]
I tested killing another player and it confirmed my suspicions. The above player took 20 hits to kill with cooldown and 7 hits to kill without cooldown. This next test player, also with no armor or other attributes, only took 7 hits WITH cooldown. And 3 or 4 hits WITHOUT cooldown.  So they are inconsistent for some reason. All other plugins disabled.

**Comment by gvlfm78** [comment]
What is the exact loadout your are using (for the players getting hit and the attacker)

**Comment by zeronerve** [comment]
Attacker: No armor, basic diamond sword with no enchants
Deadguy: No armor, basic diamond sword with no enchants

**Comment by gvlfm78** [comment]
Does this issue still occur with different combinations of attacking item and armour on the defender?

**Comment by zeronerve** [comment]
Yes. I put a diamond armor kit on the deadguys. Player A took 17 hits with cooldown disabled and Player B took 14 hits. Player A took 102 hits to kill with cooldown enabled and Player B took 93.  I've also seen this happen with stone swords and enchanted stone swords (sharpness). There's a difference in how some players received damage or how some players deliver damage inconsistently to other players. This started with my noticing that no one could kill me and one other player in PVP. Then i started noticing that some players were just much harder to kill than others. but there are no apparent differences in the players, kits, or attributes, at least that i could tell.

**Comment by zeronerve** [comment]
I'm running the latest version of Paper (1.12.2 1286) with ProtocolSupport for older clients.

**Comment by zeronerve** [comment]
The permissions log doesn't indicate any differences between the players during combat.

**Comment by zeronerve** [comment]
All players in this test used vanilla 1.8.9 with Optifine H6. No forge or other mods.

**Comment by zeronerve** [comment]
Thanks for your help with this. Any ideas?

**Comment by zeronerve** [comment]
Well I owe you an apology. It seems this issue is not related to OCM. It started happening when I installed OCM, but I just ran a test without OCM installed, and the issue still exists!!! Yuck. I'm sorry. If you have any ideas on what I should look into I'd appreciate it, but feel free to delete this ticket.

**Comment by gvlfm78** [comment]
This _might_ have something to do with the manipulation of player's data files. This would mean even when removing the affecting plugin the issue would still persist. Therefore, seeing if this is still the case on a fresh server, and then adding plugins to the fresh server might show what the actual cause is.
