### ISSUE TITLE
Tool/Item Damage Not Reverting, Other Aspects Work 

### ISSUE THREAD

**Issue by PetrichorCraft** [gvlfm78/BukkitOldCombatMechanics#147]
Hello. When I tried out this plugin, I thought it didn't do anything on my server at first. As it turns out, it's just the thing I was testing that didn't work. Most aspects of this plugin work fine for me. I can craft enchanted golden apples, prevent off-hand usage, etc. But, I cannot revert the damage of tools and swords. There are no errors in the console.

Spigot Version: 1.12.2 #131
OldCombatMechanics Version: 1.6.3
Config: https://pastebin.com/Qjrsv1vC
(I also tried defining worlds, but that didn't really affect anything, and other things worked without defining worlds)

Please note that I was not looking at the damage displayed on the items, I was actually hitting mobs and comparing damage.

**Comment by gvlfm78** [comment]
Please turn on debug mode in the config and check the messages that are sent when you use a weapon

**Comment by PetrichorCraft** [comment]
Thank you for the response! These are the messages when using (unenchanted) stone swords/axes:

![debugaxe](https://user-images.githubusercontent.com/30535390/34502901-9fed6596-efca-11e7-9772-1ba791ed9b6c.png)

![debugsword](https://user-images.githubusercontent.com/30535390/34502911-a75a4146-efca-11e7-8a1f-cff06343d5df.png)

**Comment by gvlfm78** [comment]
And is the damage displayed after "New Damage:" the damage you find is being inflicted?

**Comment by PetrichorCraft** [comment]
At the time that I posted, no. I don't remember the exact numbers, but I did check against the debug message, and it was off by at least a heart. When I checked again just now, it seems to be working. This was something on my end, I guess. I'm not really sure what made it start working, but I'm glad it did. I am sorry for posting an issue that was server-specific, and not anything you could fix. 

Thank you very much for your responses, and politeness.
