### ISSUE TITLE
Console errors for ModuleGoldenApple.onPrepareItemCraft

### ISSUE THREAD

**Issue by Goldentoenail** [gvlfm78/BukkitOldCombatMechanics#15]
nullPointerException
.onPrepareItemCraft(ModuleGoldenApple.java:39)

I am developing a custom items crafting plugin and I am receiving this error from OldCombatMechanics when I include the following code in my plugin. I can perceive no reason why this should happen!

public void onPrepare(PrepareItemCraftEvent e) {
.....Some code which filters to accept only 'my' custom recipes....
			if (!this.getConfig().getBoolean(new StringBuilder("EnabledWorlds.").append(w).toString())) {
				logger.info("A player tried to craft in an unregistered world called " + w);
				e.getInventory().setResult(new ItemStack(Material.AIR, 1));
				return;
			}
.....Other code to manage recognition of my custom recipes...
None of the rest of my code causes any issue, and I am not crafting anything with Gold or Apples!

**Comment by gvlfm78** [comment]
@Rayzr522

**Comment by Rayzr522** [comment]
Heh I'll go take a look. My modules, breaking again :P

**Comment by Rayzr522** [comment]
@Goldentoenail 
Sorry for the slow response, but the only way I could see this happening is if _somehow_ in your code maybe you are setting a recipe's result to `null`. That's all I can figure out. Obviously I need to put a `null` check in that code (should've done that anyways), but still, debug all the results for recipes that you're setting. That is the only way I can think of for a NPE to occur.
