### ISSUE TITLE
Attack speed attribute resetting with clean-up commits.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#150]
RE: https://github.com/gvlfm78/BukkitOldCombatMechanics/commit/c7c5eff9f5064abe41e08bec3fb015510979e6c9#commitcomment-26828333

Updated from dev 18 to dev 20 and now I'm getting reports of players saying the vanilla attack speed (MC 1.12.2) is back.

**Comment by Rayzr522** [comment]
Thanks, confirmed and identified. I'll have this patched in a few minutes.

**Comment by Rayzr522** [comment]
Fixed in ed6a84ba2fd9001726ad1393022294254043df28. Please re-download the new test build once it is available.

**Comment by mibby** [comment]
Confirmed fixed by the players who initially reported it being broken for them. Thanks!

**Comment by Rayzr522** [comment]
No problem, this is why you don't push to master before testing xD
