### ISSUE TITLE
Golden Apple and Fishing Rod

### ISSUE THREAD

**Issue by Rivenze** [gvlfm78/BukkitOldCombatMechanics#151]
With OldCombatMechanics, every time i eat a golden apple, the numbers of gaps dont decrease, like if i have 10 gaps, i eat one, its still 10. also whenever i right click fishing rod, it doesnt cast the rod at all.

**Comment by gvlfm78** [comment]
Those sound like two different issues that should be separated into two tickets.

**Comment by Rayzr522** [comment]
- What Minecraft server version are you running?
- What OCM version are you using?
- Are there any errors in the console?
- What is your config?

> Please upload your server log and config file to https://pastebin.com or https://hastebin.com

**Comment by Rayzr522** [comment]
Abandoned issue report, closing.
