### ISSUE TITLE
Fishing rod + Sword = can't hit player

### ISSUE THREAD

**Issue by Auntex** [gvlfm78/BukkitOldCombatMechanics#153]
Heya! I have tested Old Combat Mechanics and its a very good plugin for combat, But i have a problem, When i hit a player with Fishing rod, And next hit with a Sword, Doesn't work the hit, Who could solve it? 
Sorry for bad english.

**Comment by gvlfm78** [comment]
Are you right-clicking with the fishing rod to 'hook' the player, and then hitting them with a sword?

**Comment by Auntex** [comment]
Yeah, Then when i try to hit with a sword doesn't work, So.. I need to wait 5+ seconds

**Comment by gvlfm78** [comment]
You you reel in the player, does it then let you hit them without delay?

**Comment by Auntex** [comment]
I haven't tested, Would i need to disable the delay in config?

**Comment by gvlfm78** [comment]
First try without changing the config
