### ISSUE TITLE
Armor bars disappear on latest build 22

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#154]
I downgraded to build 18 and it fixed it.

**Comment by Fonzee9** [comment]
Basically when you wear armor at the bottom you see Armor bars and on build 22 it somehow causes them to disappear.

**Comment by gvlfm78** [comment]
Does build 21 work? Or 20? Or 19?

**Comment by Fonzee9** [comment]
Not sure haven't tested those

**Comment by gvlfm78** [comment]
@Fonzee9 This should be fixed in version 1.6.5
