### ISSUE TITLE
1.7. TnT mechanism

### ISSUE THREAD

**Issue by kamber5** [gvlfm78/BukkitOldCombatMechanics#155]
Hi!

We have a Factions server on 1.12. version of minecraft, and the players are complaining that they cant make cannons such as sand cannons etc.
It would be really cool if this gets implemented in this plugin, it would help alot :)

Best regards!

**Comment by Auntex** [comment]
Heya! That is in the To Do List, You can see on the Wiki page here: https://github.com/gvlfm78/BukkitOldCombatMechanics/wiki/To-Do-List
Well, Thats unfinished. :(

**Comment by kamber5** [comment]
Oh i didnt see.

This update would be really really helpfull :)

**Comment by Rayzr522** [comment]
Is there an exact description of how the TNT mechanics changed between 1.7 and 1.8+? Because I’ve heard they changed, but I’m not exactly sure how.

**Comment by kamber5** [comment]
In 1.9. and up versions cannons got totally destroyed.

**Comment by Rayzr522** [comment]
“cannons got totally destroyed” is highly vague. How exactly did the mechanics change? In what way does the TNT behave differently?

**Comment by kamber5** [comment]
Here is a plugin with some of the old features that are not working. You can see what the features do in the gifs

https://www.spigotmc.org/resources/oldmechanisms.36659/

**Comment by LethalSh0tt** [comment]
I heard sponges work differently too in the newer versions. If they do, could you also add 1.7 sponges

**Comment by Rayzr522** [comment]
Possibly, but that seems like a rather non-critical feature to change right now. If you can confirm that they have changed and find out exactly how they have changed, then please create a separate feature request describing the changes.

As for the TNT mechanics, I've *started* a bit of work on them (35a5ab055459e9c33a86af8c1a457b85661e000a), but there are certain Bukkit limitations that make this exceptionally difficult to deal with, such as no events that are called when a TNT is summoned.

**Comment by kamber5** [comment]
Will you try to recreate how the sand works in that module.
- How it is now:
https://media.giphy.com/media/26xBFhCndFYDkgGwU/source.gif
- How it should be:
https://media.giphy.com/media/26xBSpSeQPeBDzXqg/source.gif

And i found a clip explaining the problems for cannons
https://www.youtube.com/watch?v=wzx9d3jujVQ

**Comment by LethalSh0tt** [comment]
For 1.7 tnt mechanics, isn’t that the reason paperspigot is there? Tell me if I’m wrong.

**Comment by kamber5** [comment]
We tried paperspigot but it really didnt help alot.

**Comment by kamber5** [comment]
How is work progressing :)

**Comment by kamber5** [comment]
Hi!

Any news about this?

**Comment by kamber5** [comment]
Helloooo

**Comment by Rayzr522** [comment]
The only way to do this is with some seriously hacky stuff called ASM; essentially, modifying the bytecode of classes at runtime. Not only is this not always safe, but it is also highly difficult in newer version of Java (9+). I think that for now, unless an alternative method of detecting TNT spawning can be found, this issue will simply have to go unresolved. I will close this now. 

Feel free to reopen the issue if you find any new information about this :)
