### ISSUE TITLE
Timings stuff

### ISSUE THREAD

**Issue by RainOfPain125** [gvlfm78/BukkitOldCombatMechanics#157]
Completely new to timings, but I was told it had something to do with servers lag

One of the biggest culprits is OCM

![image](https://user-images.githubusercontent.com/33137905/35245503-9bf2700e-ff91-11e7-9e58-07002efbd80b.png)

**Comment by Rayzr522** [comment]
That shouldn't even be possible. In fact, the only possible reason I can see for that to take any amount of time at all is if somehow the saving of the playerdata was being bottlenecked. What server version and OCM version are you using? Additionally, when did you begin to experience problems with lag on your server?

**Comment by RainOfPain125** [comment]
git-Paper-1305
version 1.6.3

I mean I am using a hard drive, but It's the latest class of Seagate 7200RPM drives so it should be just fine for a hard drive. Me and my friend realized one day when logging onto the server that our ping skyrockets at login but tones down after a while. I am hosting the server off my own computer and get around 120 ping after login, but dies down to 5-10

**Comment by RainOfPain125** [comment]
Heres some extra info just incase

Config https://pastebin.com/vrP4vXPv
 Plugins (51): AreaShop, Auctions, AutoSave, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChestRestock, ChestShop, Citizens, CombatLogX, CoreProtect, CrazyCrates, EpicRename, Essentials, EssentialsChat, FactionChat, Factions, HolographicDisplays, HolographicScoreboard, InfoBook, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PlayTime, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, Vault, Votifier, WarningCategories, Wild, WorldEdit, WorldGuard

**Comment by gvlfm78** [comment]
Please try the [latest test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/) of OCM to check if the issue has anything to do with the update checker.

**Comment by Rayzr522** [comment]
Abandoned issue, closing now.
