### ISSUE TITLE
Armor values missing

### ISSUE THREAD

**Issue by RainOfPain125** [gvlfm78/BukkitOldCombatMechanics#159]
I suspect it might be this plugin considering this plugin does have to do with modifying armor tags like armor toughness

https://www.planetminecraft.com/forums/minecraft/help/armor-values-missing-564466/

Though I'm not entirely sure..?

**Comment by RainOfPain125** [comment]
heres a video

https://youtu.be/qWcjW5t1IhU

**Comment by kamber5** [comment]
You probably have module "old-armour-strength" enabled :)

**Comment by RainOfPain125** [comment]
o///o

I thought that meant something else....

okay....

I feel stupid now...
