### ISSUE TITLE
Jenkins server is down.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#16]

**Comment by gvlfm78** [comment]
The Jenkins server has been moved over to https://jenkins-gvl.rhcloud.com/

**Comment by mibby** [comment]
May want to update the readme on the git page and the spigot page.

**Comment by gvlfm78** [comment]
I hadn't realised there were links for it there. I've update them on all three websites.

**Comment by mibby** [comment]
Jenkins go down again? :(

**Comment by gvlfm78** [comment]
If it says it's down for maintenance or such usually reloading the page a couple time forces it to wake up again. Sometimes you have to close the tab and open another to force reload and not pull the page from the cache.

**Comment by mibby** [comment]
Quite odd. It was down entirely, unreachable. But seems to be back up now, so all is good. :)
