### ISSUE TITLE
Collision is not disabled

### ISSUE THREAD

**Issue by dunaland1** [gvlfm78/BukkitOldCombatMechanics#160]
I have this in the config:
disable-player-collisions:
  # This is to disable player collision
  # This is now compatible with scoreboard and tablist-editing plugins
  enabled: true
  worlds: []
Yet player collision is still enabled. Spigot 1.12.2, latest version.

**Comment by LethalSh0tt** [comment]
If you have ViaVersion, you can disable it

**Comment by NachoMans** [comment]
If you type /viaver autoteam, you can disable player collisions. I don't use this feature since I already have paperspigot.

**Comment by gvlfm78** [comment]
And what does paperspigot do instead?

**Comment by NachoMans** [comment]
Paper Spigot has an option to disable player collisions. Also there are https://paper.readthedocs.io/en/paper-1.11/features/ for a list.
