### ISSUE TITLE
Armor values missing / wrong

### ISSUE THREAD

**Issue by RainOfPain125** [gvlfm78/BukkitOldCombatMechanics#162]
version 1.6.3

if
old-armour-strength:
  This is to set armour strength values as in pre-1.9
  enabled: false

then my armor will have the normal armor values and normal armor toughness

if
old-armour-strength:
  This is to set armour strength values as in pre-1.9
  enabled: true

then my armor will have 9999 armor toughness HOWEVER will have no armor value (no armor points in the hotbar when wearing armor)

Setting it to true ultimately makes armor useless as it thinks you're not wearing armor

my full config - https://pastebin.com/ikNLGrhN

**Comment by RainOfPain125** [comment]
seems so.

**Comment by gvlfm78** [comment]
Ok I'm going to have a look at this at some point to see what th exact error is

**Comment by gvlfm78** [comment]
In fact, I did not make that change and @Rayzr522 might know something more about what might be causing this issue

**Comment by Rayzr522** [comment]
@RainOfPain125 have you tried test build 22? Because I had that same problem on my server, but I fixed it in one of the commits after 1.6.3 was released. However, if they are not wearing the armor when you upgrade from the broken version to the fixed version, you may have to `/ocm reload` once they put it on.

Basically:
1. Update to the latest test build (22)
2. Put some broken armor on
3. Do `/ocm reload`

Please let me know if that fixes things.

**Comment by RainOfPain125** [comment]
I am using 1.6.3. If you mean there is a ver higher your wrong as that isn't the case on the jenkins page

Here is a video of me testing it some more -
https://www.youtube.com/watch?v=dDTbCof5Ae8&feature=youtu.be

**Comment by Rayzr522** [comment]
I'm saying to get build 22 on the Jenkins page, which is not 1.6.3. Are you using the [latest version from the Jenkins page](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics)?

**Comment by Rayzr522** [comment]
Did you try putting some broken armor on and doing `/ocm reload`? Also, server logs would help.

**Comment by gvlfm78** [comment]
@RainOfPain125 This should now be fixed in version 1.6.5

**Comment by RainOfPain125** [comment]
Even if it is I'll wait for you guys to smooth out the wrinkles in this plugin before I think about introducing old mechanics again. Too much PTSD for my players experiencing bugs from it

**Comment by Rayzr522** [comment]
All your current issues (other than the mcMMO problem) should be solved, but I understand. However, if no one were to use our plugin and find these bugs, we would never know about them :p
