### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by MikhailY** [gvlfm78/BukkitOldCombatMechanics#164]
The plugin works fine, but why can't I uninstall it? help please.
I removed the jar file

**Comment by gvlfm78** [comment]
Did you stop the server before removing the jar file?

**Comment by MikhailY** [comment]
I first removed the jar and then restarted

**Comment by gvlfm78** [comment]
Did you:

1. Stop the server
2. Remove the Jar
3. Restart the server?

Or did you do something even slightly different?

**Comment by MikhailY** [comment]
1. Remove the Jar
2. Stop the server
3 .Start the server

**Comment by NachoMans** [comment]
Try what he said

**Comment by MikhailY** [comment]
If I have already deleted the jar file

**Comment by NachoMans** [comment]
Try downloading OCM again and take it out the way he did it.

**Comment by gvlfm78** [comment]
If that still doesn't work follow the instructions [here](https://github.com/Rayzr522/OCMFixer).

**Comment by MikhailY** [comment]
Thanks
