### ISSUE TITLE
Bow Boosting option not working

### ISSUE THREAD

**Issue by iBradyy** [gvlfm78/BukkitOldCombatMechanics#165]
People are not able to hit themselves with their own arrows. This also disallows them to Bow boost.
The option ''disable-bow-boost'' has been disabled in the config, but it seems not to work.

Once you shoot an arrow in the air, and you try to get hit by it, it will just drop on top of your head.

disable-bow-boost:
  - This is to stop players from boosting themselves forward by hitting themselves
  - while running with a punch II arrow from their bow
  - This module just stops them from hitting themselves with arrows entirely
  enabled: false
  worlds: []

Server Version: Paperspigot 1.12.2
OldCombatMechanics Version: 1.6.3
config-version: 25
We are also using ProtocolSupport to allow 1.7 and higher to join.

**Comment by gvlfm78** [comment]
Ok can you please enable _debug_ in the config.yml and reload the server and check in the server logs if OCM says the BowBoost module is being activated?
