### ISSUE TITLE
Disabling collisions doesn't work

### ISSUE THREAD

**Issue by Stephanech** [gvlfm78/BukkitOldCombatMechanics#166]
The title is a little self-explanatory.
I have this in my config.yml:

`disable-player-collisions:
  # This is to disable player collision
  # This is now compatible with scoreboard and tablist-editing plugins
  enabled: true
  worlds: [Survival,kitpvp,coleccion,pvp,skyspawn,lobby,nether,ender,aventura,spawn,mapasskywars,recursos]`

But there are still collisions in all the worlds specified, how can I solve this problem?

Spigot 1.12
OldCombatMechanics 1.6.2

**Comment by gvlfm78** [comment]
Do you know of any plugins on your server that might be interfering?

**Comment by gvlfm78** [comment]
Also this is a potential duplicate of #160

**Comment by gvlfm78** [comment]
Duplicate of #160
