### ISSUE TITLE
Player Collision

### ISSUE THREAD

**Issue by RickIsThicc** [gvlfm78/BukkitOldCombatMechanics#167]
I understand that this issue has been reported before, but an answer never seemed to be supplied. Essentially player collision is not disabled even though I have it disabled in the config.

Config: https://pastebin.com/qqgX257z (I have also set it so that the world space is empty, but it still didn't work).

Plugin Version: 1.6.3

Spigot Version: Spigot 1.12.2 # 131

Plugins: https://gyazo.com/d214ca1dfc5028b1a6fc9508787e9d49

**Comment by gvlfm78** [comment]
Duplicate of #160

**Comment by RickIsThicc** [comment]
You never fixed the issue in the other ticket though? I'm not running paper or using viaversion.

**Comment by gvlfm78** [comment]
I never got enough information to do so. This discussion should be continued over there.
