### ISSUE TITLE
Bug nbt tags

### ISSUE THREAD

**Issue by tantanpro1612** [gvlfm78/BukkitOldCombatMechanics#168]
You can watch this video to understand the problem. Thanks !
( This problem was overcome when I remove plugin OCM )
VIDEO: https://youtu.be/HYeVvwYT0Kc
I use paper spigot: 1.10.2 & OCM latest

**Comment by gvlfm78** [comment]
What is the problem?

**Comment by tantanpro1612** [comment]
NBT TAGS values has changed when i remove it
It will give value +9999

**Comment by gvlfm78** [comment]
Yes, that's what it should be doing. When you put armour on it should give it +9999 toughness in order to make it work like in 1.8, and when you take it off it is set back to the original value so that if you were to remove the plugin it wouldn't stay.
