### ISSUE TITLE
Armour damage reduction seemingly not accurate to 1.8

### ISSUE THREAD

**Issue by corpzz** [gvlfm78/BukkitOldCombatMechanics#17]
are there any limitations to how much armor can be like it was in 1.9? I went on 1.8 single player, and it took 4 hits for a zombie to take a full heart in full diamond armor, and on 1.10.2 with oldcombatmechanics installed, i took 2 hits from the zombie in diamond armor and it dealt a full heart. ive cranked up the armor strength value but to no avail i still take the same damage. i know that in 1.8, it was 80% damage reduction.

**Comment by Rayzr522** [comment]
@gvlfm78

**Comment by gvlfm78** [comment]
I answered on Spigot, but it's better if issued are resolved here.

That is strange, there must be some other variable affecting it. You can see the spreadsheet I created [here](https://yadi.sk/i/vSnTU42YxNRXr) that has the calculations for the values 1.8 to 1.9 with OCM. You must make sure enchantments aren't affecting your test. You can also try turning debug mode on in the OCM config.yml which should tell you the damage done and what was applied.

**Comment by gvlfm78** [comment]
@corpzz I could not replicate this issue in the newest OCM.
