### ISSUE TITLE
Players can't take off their armor

### ISSUE THREAD

**Issue by Kimi147** [gvlfm78/BukkitOldCombatMechanics#170]
Players cant take off their armor when they equip it
Im using paperspigot 1.12.2 latest
Using latest version of your plugin

My config - https://pastebin.com/deEK440x

Please fix asap because when i remove your plugin everything is okay with armors

**Comment by Kimi147** [comment]
When someone has op, everything is working fine, what the fuck?

**Comment by Rayzr522** [comment]
Please upload your latest server log to http://pastebin.com and post it here.

**Comment by Kimi147** [comment]
Heyy, i found out that if i disable this option:
old-armour-strength

Everything is fine, but i still want the old armour strength? Got any ideas? Do i still need to upload a log?

**Comment by Kimi147** [comment]
Im also using CrazyEnchantments plugin and i have some custom enchants for armors, but i dont think thats an issue because the bug still ocurrs with armors without any enchants

**Comment by Kimi147** [comment]
I just tested armors on 1.8 and on 1.12 and actually its completely the same damage without this option enabled in your plugin? Am i missing something?

**Comment by Rayzr522** [comment]
Yes, still upload the logs. If there is a problem with the old armor strength module, then we need the logs so we can diagnose and solve the issue.

**Comment by Rayzr522** [comment]
Probably the reason why the damage was the same was because you were most likely using armor that had already been modified by OCM.

**Comment by Kimi147** [comment]
Well i dont think so because i had new set from gamemode after restarting (not reloading) server with that option disabled :/

**Comment by Kimi147** [comment]
Do i need to send you logs with enabled/disabled armor feature in your plugin?

**Comment by Rayzr522** [comment]
Enable the armor feature and send the logs. And trust me, the armor mechanics *did* change between 1.8 and 1.9+.

**Comment by Kimi147** [comment]
Okay i will trust you even if this is so strange haha
I found out that if you are in creative gamemode everything is okay (even if you are not op) and also if you are OP everything is okay

Here is the full latest log with enabled feature - https://pastebin.com/wRGs2VBN

**Comment by Kimi147** [comment]
Do i maybie need to enable debug in your plugin?

**Comment by Kimi147** [comment]
I can see that you wrote "passion for programming" in your profile desc xd

**Comment by gvlfm78** [comment]
Well in the meantime yes, we would like a log with debug mode enabled

**Comment by Rayzr522** [comment]
We still need a log file, preferably with debug mode enabled. Without it we can't do anything to help you.

**Comment by Rayzr522** [comment]
Abandoned issue, closing now.
