### ISSUE TITLE
player collisions per world are not working - not working with MVdWPlaceholderAPI

### ISSUE THREAD

**Issue by AmazedMender16** [gvlfm78/BukkitOldCombatMechanics#173]
Version: Latest
Server Version: Spigot 1.12.2 (latest)

When trying to set per world collisions it doesnt work it basically applies everywhere
disable-player-collisions:
  enabled: true
  worlds: [world001,world002]

**Comment by AmazedMender16** [comment]
When MVdWPlaceholderAPI is loaded the entire player collisions stops working

**Comment by gvlfm78** [comment]
Ok so do you mean that the no-collisions feature is not working at all or that it works in all worlds when it should just be working in those specified?

With the above configuration, do worlds world001 and world002 have player collisions enabled?

And what changes relative to the above situation when MVdWPlaceholderAPI is loaded/unloaded?

**Comment by AmazedMender16** [comment]
the world option should enable that only in these worlds the player collision is disabled right? like you cannot push eachother. 

When MVdWPlaceholderAPI is loaded the entire collisions stops working no matter what world. it just stops you can basically push any player.

**Comment by AmazedMender16** [comment]
Any updates about this issue?

**Comment by gvlfm78** [comment]
I'm assuming this is related to issue #160 , just that you actually bothered to give more info than just "it doesn't work"... The problem is that this module is extremely fiddly and can easily break because of other plugins interfering.

**Comment by AmazedMender16** [comment]
I assume so... i have done some testing and it doesnt happen when mvdwplaceholderapi is unloaded or not installed. Then it all works fine besides the world option

**Comment by AmazedMender16** [comment]
Would love to see a fix for this.

**Comment by AmazedMender16** [comment]
Any ETA date for a fix?

**Comment by I-Al-Istannen** [comment]
@AmazedMender16 
Do you use any scoreboard plugin? If so, can you tell us if it works if you remove the scoreboard plugin but leave MVdWPlaceholderAPI there?

Can't reproduce it with:
```
Plugins: TNTSpawnEvents, OldCombatMechanics, MVdWPlaceholderAPI, Flash

[20:46:50 INFO]: This server is running CraftBukkit version git-Spigot-4bd94dc-9ab298d (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:46:50 INFO]: Checking version, please wait...
[20:46:51 INFO]: You are 31 version(s) behind
```

**Comment by AmazedMender16** [comment]
I do run featherboard but i have tried loading up the server only with oldcombatmechanics and mvdwplaceholderapi and i still wasnt able to walk thru the players. When i restarted and removed the mvdwplaceholderapi i was able to walk thru the players

**Comment by I-Al-Istannen** [comment]
@AmazedMender16 Can you tell me the minecraft version, the OCM version and the output of `pl`?

**Comment by AmazedMender16** [comment]
They all running the newest versions

**Comment by I-Al-Istannen** [comment]
@AmazedMender16 
[Have a look at this](https://imgur.com/a/fAHS7Br)

This is what it looks like for me. I am not sure if gvlfm could reproduce it, but without a good way to reproduce it, debugging is essentially impossible.

```
[OldCombatMechanics] Enabling OldCombatMechanics v1.6.5
[OldCombatMechanics] OldCombatMechanics v1.6.5 has been enabled
[MVdWPlaceholderAPI] Enabling MVdWPlaceholderAPI v2.5.1

[21:13:07 INFO]: This server is running CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:13:07 INFO]: Checking version, please wait...
[21:13:08 INFO]: You are running the latest version
```

That is what I am running, what do you use?

**Comment by AmazedMender16** [comment]
I have rechecked it now seems to be AnimatedNames that is causing it to not work. When i remove that plugin it seems to work just fine .....

**Comment by gvlfm78** [comment]
Eeh well the point of OCM is to not have any dependencies at all, so if that is the only fix then it would have to be coded using reflection. I might have a look at this in about two weeks when I will have plenty of time, unless @Rayzr522 works on it first.

**Comment by I-Al-Istannen** [comment]
@gvlfm78 As I said, you can also roll it yourself. It is just not as pleasant and more prone to breaking in the future (if the protocol changes) than using ProtocolLib.

I just tried it out though and my classes are still working fine and are able to intercept and modify the outgoing packets, so it seems like nothing has really changed in the past year. If you wanna write your own the implementation of [TinyProtocol](https://github.com/dmulloy2/ProtocolLib/tree/master/modules/TinyProtocol) can be found here and my own [here](https://github.com/I-Al-Istannen/BukkitUtilities/blob/master/Packet/src/main/java/me/ialistannen/bukkitutilities/packet/PacketManager.java). I am posting mine too as TinyProtocol does a few things you don't need here that increase the complexity by a lot IMHO.

**Comment by I-Al-Istannen** [comment]
@AmazedMender16 Can you try [this](https://www.dropbox.com/s/opi992s533k5hup/OCM.jar?dl=1) version of OCM?

If you are sceptical of it and don't want to download a jar from a weirdo on the internet, I can push my fork to github alongside with instructions on how to build it.

Note that it disables collision everywhere, not just in the worlds in the config.

**Comment by AmazedMender16** [comment]
But this does not fix the issue with the original OCM :)

**Comment by I-Al-Istannen** [comment]
@AmazedMender16 Yes, but if it works it at least fixes the issue and one can work on doing something similiar in OCM. At the moment it is my *guess* that it will solve the issue, not hard proof as I don't own the plugin in question.

**Comment by AmazedMender16** [comment]
@I-Al-Istannen The version you send earlier has fixed the issue..
