### ISSUE TITLE
Armour strength bug

### ISSUE THREAD

**Issue by iamharak** [gvlfm78/BukkitOldCombatMechanics#182]
Hi!

I used a latest version of the OldCombatMechanics plugin however in the same way the armour strength bug.
Please fix it, or help me, please.

/Sorry, I used a Google Translate./

**Comment by Rayzr522** [comment]
Please try updating to the [latest development build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastBuild/) of OldCombatMechanics. There were a lot of bugs that have been fixed in the latest builds.
