### ISSUE TITLE
Uninstallation Help

### ISSUE THREAD

**Issue by rykea1** [gvlfm78/BukkitOldCombatMechanics#186]
## Info

- Server version: 1.12
- OldCombatMechanics version: 1.6.5
- Server log file: https://hastebin.com/vohiyaqobi.sql
- OldCombatMechanics config file:  https://hastebin.com/aduxuzovik.bash

## Problem Description
> I can't seem to uninstall the plugin, whenever I delete the jar file, restart the server and try playing, it's as if I didn't do anything in the first place

**Comment by Rayzr522** [comment]
Are you saying that upon restarting, the players still have no attack cooldown?

**Comment by rykea1** [comment]
yes, pretty much

**Comment by Rayzr522** [comment]
Is it just for you or for all users on your server?

**Comment by rykea1** [comment]
everyone on the server

**Comment by rykea1** [comment]
and there isn't a attack indicator either

**Comment by Rayzr522** [comment]
Hmmm, strange. You stopped the server, removed the JAR file, and then started it back up again?

**Comment by rykea1** [comment]
what?

**Comment by Rayzr522** [comment]
Alright. Please try using [OCMFixer](https://github.com/Rayzr522/OCMFixer) to fix it.

**Comment by rykea1** [comment]
Thanks ^^, I'll see if it works

**Comment by rykea1** [comment]
I know this is a stupid question but how do I install the  OCMfixer, I'm confused

**Comment by Rayzr522** [comment]
Read the installation section on that page. There is a link to the releases page where you can download the OCMFixer JAR file. It's just a plugin. There are also instructions on that page for how to use OCMFixer.

**Comment by rykea1** [comment]
well I tried that but when I do /read it says that there isn't a command for that

**Comment by Rayzr522** [comment]
You placed the OCMFixer JAR file into uour server plugins folder and restarted your server, right?

**Comment by Xandervyvey** [comment]
> You placed the OCMFixer JAR file into your server plugins folder and restarted your server, right?

I have the same problem

> You placed the OCMFixer JAR file into your server plugins folder and restarted your server, right?

I have the same problem pls help!!
