### ISSUE TITLE
OCM and McStats.org

### ISSUE THREAD

**Issue by I-Al-Istannen** [gvlfm78/BukkitOldCombatMechanics#190]
## Info
OCM seems to use mcstats.org (or at least the provided MetricsLite class seems to do). That project seems to have pretty much died by now. The website times out, the metrics plugin reports a `500` and the issues on the github project are just piling up.

The most likely successor seems to be `bStats` from what I read, so you might want to think about migrating or just killing metrics altogether.

**Comment by gvlfm78** [comment]
OCM has supported bStats for quite a while now, and MCStats has been in a state of existing every now and then for the past two years.

**Comment by I-Al-Istannen** [comment]
Interesting. I have no idea why that didn't show up in my initial search, might have been limited by IDEA to only one directory. It likes to be funky sometimes. Apologize for the inconvenience :)
