### ISSUE TITLE
WARN [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@349562347)

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#191]
WARN [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@349562347)

paper spigot 1.12.2 
latest version of plugin

**Comment by I-Al-Istannen** [comment]
Are you on this ![this](https://user-images.githubusercontent.com/20284688/41822085-9976e50e-77ea-11e8-970f-81aa451a3baf.png) version or a newer one?

If you are not you should update to that, as it fixed a bug that would cause that message to be spammed.

The jenkins job seems to be dead, so the *currently* most up to date version can be found [here](https://www.dropbox.com/s/2owxriascklqco2/OldCombatMechanics.jar?dl=1)

**Comment by gvlfm78** [comment]
The Jenkins server should be back up now

**Comment by gvlfm78** [comment]
The Jenkins server should be back up now

**Comment by leoncp9** [comment]
thank

**Comment by Rayzr522** [comment]
Did the updated version of OldCombatMechanics fix your issue?

**Comment by leoncp9** [comment]
yes

**Comment by Rayzr522** [comment]
Alright.
