### ISSUE TITLE
Free Shields from Armor Stands Bug

### ISSUE THREAD

**Issue by pinkpig3777** [gvlfm78/BukkitOldCombatMechanics#192]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.5
- Server log file: https://pastebin.com/k0BcBYK8
- OldCombatMechanics config file: https://pastebin.com/JCbDqRUp

## Problem Description
>  Players can place a sword on a armor stand then it will have a shield automatically appear on the armor stand and then they can take the shield off. Thus allowing the ability to get free shields from nothing.

**Comment by Rayzr522** [comment]
I am unable to reproduce this bug on either v1.6.5 or on the latest dev build. Could you create a video demonstrating it?
