### ISSUE TITLE
fix thi spam on console

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#194]
i use latest version
i get this spam on console when i stopped server
WARN [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1447163556)

**Comment by I-Al-Istannen** [comment]
Define latest version please.
Do you use at least [this](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/42/) build?
It was released at `10.06.2018 17:33:03`.

**Comment by leoncp9** [comment]
i use this https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/44/ now is fixed
