### ISSUE TITLE
Knockback of fishing rod is inconsistent / delayed

### ISSUE THREAD

**Issue by UnNamedAndre** [gvlfm78/BukkitOldCombatMechanics#197]
## Info

- Server version: Latest Paperspigot 1.12.2
- OldCombatMechanics version: the last 1.6.5
- Server log file: there isn't
- OldCombatMechanics config file: 25

I enabled old fishing rod.. when i throw to an enemy, it works sometimes.. and sometimes don't knockback them.. but when it knockbacks, then, i'm not able to attack other players for a tot of time, 2-3 sec, this problem is related just for the fishing rod, i'm using it in a practice server. Please fix this.

**Comment by Rayzr522** [comment]
We need the server log file and the OldCombatMechanics config file. Every server has a server log file, so I'm not sure what you mean by "there isn't". Also, giving us a random number for the OldCombatMechanics config file is of little help, we need the config file itself.

**Comment by gvlfm78** [comment]
@UnNamedAndre please enable debug mode in the config.yml and look for any debug messages in the console or between the affected players.

**Comment by UnNamedAndre** [comment]
nothing appears, fix

**Comment by I-Al-Istannen** [comment]
IS there any, at least partially, reliable way to reproduce the problem? E.g. does it appear more often if you do something specific?

**Comment by UnNamedAndre** [comment]
i tell u the problem.. when i throw ROD, sometimes it knockback like 1.8, sometimes not.. when it hits, i won't be able to hit another person for at least 3-4 sec, then, all works, until i throw a rod, when i throw a rod, i forgot to say that, i'm not able also to pvp if i always throw it.

**Comment by I-Al-Istannen** [comment]
Remove `Better Combat` and try again please @UnNamedAndre

**Comment by UnNamedAndre** [comment]
i put better combat after the issue, when it gave the error anyway, i fixed with that plugin, but i want to use all in your plugin.., that's why i told u to fix ahhaahah

**Comment by I-Al-Istannen** [comment]
I can reproduce the error when having both, Better Combat *and* OCM installed. Just OCM works fine for me.

Can you try it on a test server without *any* plugin except for OCM?

**Comment by UnNamedAndre** [comment]
i've alreay done it, i'm using paperspigot 1.12, i don't know if the problem is that.

**Comment by I-Al-Istannen** [comment]
Can you send the log of trying it out on a *clean* Paper server then, with only OCM installed? One of the hardest parts of fixing a bug is actually tracking down where it originated, which is why we are asking all of these questions :)

**Comment by Rayzr522** [comment]
If you have any further information about this, feel free to re-open the issue.
