### ISSUE TITLE
Hand goes invisible when swapping between worlds.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#2]
When teleporting to a different world, your hand / tool goes invisible and you do no damage. Reloading OCM or relogging fixes the problem.

http://paste.ubuntu.com/18129754/

Tested with ```general-attack-speed: 16``` and ```general-attack-speed: 1024```.

**Comment by Rayzr522** [comment]
I just designed and migrated us over to a new modular code system and something didn't get changed right. It's now fixed, get the latest build here:
https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/
