### ISSUE TITLE
PlayerItemHeldEvent error + playerWeakReference warning

### ISSUE THREAD

**Issue by AfkF24** [gvlfm78/BukkitOldCombatMechanics#205]
## Info

- Server version: Paper 1.12.2, build 1513*
- OldCombatMechanics version: 1.6.6 (latest)
- Server log file: /
- OldCombatMechanics config file: https://hastebin.com/orazukoyud.bash

## Problem Description
> Been getting the following error every now and then: https://hastebin.com/vehepetehu.rb , as well as "playerWeakReference" warning being spammed ocasionally (#201)

**Comment by I-Al-Istannen** [comment]
Hm.
So. When the player changes the hotbar slot, the task is canceled and the state restored.
```java
tryCancelTask(e.getPlayer().getUniqueId());
restore(e.getPlayer());
```
This call to restore is the one erroring and to be more specific, it is this:
```java
if(p.isBlocking()) //They are still blocking with the shield so postpone restoring
    postponeRestoring(p); // <--- THIS
```
And inside `postponeRestoring` this:
```java
correspondingTasks.get(id).cancelAll();
```

As we see, this task was just cleared. This means, that if the player is still considered blocking when the hotbar change event fires, this error could occur.

After a small test, this does indeed lead to a NPE with an identical stacktrace.

**Comment by Rayzr522** [comment]
This should now be fixed in [the latest dev build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/53/).
