### ISSUE TITLE
Players can not create strenght potion when old alchemy stand is enabled

### ISSUE THREAD

**Issue by piter909** [gvlfm78/BukkitOldCombatMechanics#21]
Players can not create strenght potion when old alchemy stand is enabled.
It is because they can not put blaze powder to brewing slot (not fuel).

**Comment by Rayzr522** [comment]
@gvlfm78, this is your module, just add a slot check and this'll be fixed :P

**Comment by gvlfm78** [comment]
@piter909 Can you try with [this test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/21/) and see if the bug persists?

**Comment by piter909** [comment]
Plugin updated. After restart (tomorrow), I will post if it works or not :) Thanks!

**Comment by gvlfm78** [comment]
Do you not have plugman?

**Comment by piter909** [comment]
Reloaded with plugman. I was not doing it just for safety (crash risk etc.).
Plugin still does not work. I can now click on blaze powder and put it correctly. It is starting brew, but.. When I close stand and reopen it, brewing is stoping.

**Comment by gvlfm78** [comment]
Yeah I realised too late. I believed I have fixed that in [this other test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/22/).

**Comment by gvlfm78** [comment]
@piter909 Does it work with the test version?

**Comment by piter909** [comment]
I will test it today.

**Comment by gvlfm78** [comment]
@piter909 So does it work? I will be releasing a new OCM version very soon
