### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by AfkF24** [gvlfm78/BukkitOldCombatMechanics#211]
## Info

- Server version: Paper 1.12.2, build 1513
- OldCombatMechanics version: 1.6.6
- Server log file: /
- OldCombatMechanics config file: https://hastebin.com/orazukoyud.bash

## Problem Description
> Just got this error after a player connected to the server https://hastebin.com/oliragilev.cs

**Comment by AfkF24** [comment]
Just realized that this was already reported, #208 

Could the plugin [TAB](https://www.spigotmc.org/resources/tab-1-8-x-1-13-x-reborn.57806/) be the cause of this?
`[21:26:47] [Server thread/INFO]: [TAB] Failed to create packet_handler for PLAYER, retrying...`

**Comment by I-Al-Istannen** [comment]
Can you try #210, you can find it over on my fork of this repo, but I will attach a compiled version for you.
[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2237276/OCM.zip)

**Comment by AfkF24** [comment]
Yup. Just from a brief testing, it seems to be fixed.

**Comment by Rayzr522** [comment]
Has this issue been resolved? If so, please close this issue report.

**Comment by AfkF24** [comment]
Yup, my bad
