### ISSUE TITLE
OldCombatMechanics  v1.6.6

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#213]
## Info

- Server version: paper spigot 1.8.8
- OldCombatMechanics version: v1.6.6
- Server log file: download
https://drive.google.com/open?id=1MsNMQApary_kMTGz3FaYkRDk2jX5I_5d
- OldCombatMechanics config file: download
https://drive.google.com/open?id=1HVkAiICPtuxQPetRPggp87mjiI18SPvk

## Problem Description
> Error occurred while enabling OldCombatMechanics v1.6.6 (Is it up to date?)

**Comment by I-Al-Istannen** [comment]
It's because Minecraft 1.8.8 doesn't have shields.

But why are you running a plugin designed to restore 1.8 combat *in 1.8* ? That seems a bit odd, as the combat *already is 1.8* because that is your server version.

**Comment by leoncp9** [comment]
ooooooooooooooo sorry, lel
