### ISSUE TITLE
Golden apple recipe error on load

### ISSUE THREAD

**Issue by JeffHD** [gvlfm78/BukkitOldCombatMechanics#215]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file:  https://pastebin.com/4FuvNadP
- OldCombatMechanics config file:  https://pastebin.com/3rX11KQj

## Problem Description

On server start the error I become the error:
Error occurred while enabling OldCombatMechanics v1.6.6 (Is it up to date?)

Server is the latest version of Spigot 1.12.2 and OldCombatMechanics version 1.6.6

**Comment by Rayzr522** [comment]
Did this error occur after a clean restart, or did this happen after you `/reload`ed the server? It looks like it's complaining about a recipe being registered twice.

**Comment by Rayzr522** [comment]
What other plugins do you have installed?

**Comment by JeffHD** [comment]
The plugins are:
ChatEx, ChestShop, CoreProtect, Essentials, LibsDisguises, Multiverse, OpenInv, PEX, PlaceholderAPI, ProtocolLib, EconomyPlugin, TimeisMoney, Vault, VotingPlugin, Cubit, Dynmap, mcMMO, WorldEdit, WorldGuard and one of my plugins but nothing with recipes

**Comment by gvlfm78** [comment]
@JeffHD Please open a new issue if this problem is still present in the newest dev build.
