### ISSUE TITLE
PlayerJoinEvent to OldCombatMechanics v1.6.6

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#216]
## Info

- Server version: paper spigot 1.12.2 b1508
- OldCombatMechanics version: 1.6.6
- Server log file: download , open with notepad++
https://drive.google.com/open?id=16SSHNbSF5ctG8S1qORAhGPX5pm4C2_1v
- OldCombatMechanics config file: 

## Problem Description
> i get spam on console

**Comment by detobel36** [comment]
Duplication of #211

**Comment by Rayzr522** [comment]
You already reported this issue (#208). I'm going to close this issue as it's an exact duplicate. Please try [the latest dev build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/57/) and see if that fixes your problem. If you would like further assistance with this, please re-open #208.
