### ISSUE TITLE
Inportant question.

### ISSUE THREAD

**Issue by DutchUser** [gvlfm78/BukkitOldCombatMechanics#22]
Hello.

How can i set every's players attack speed armour etc, statz to default? (The way how 1.8 and higher worked)

**Comment by gvlfm78** [comment]
Have a look at issue #11

**Comment by DutchUser** [comment]
I have everyting to false but few players still have no cooldown.

**Comment by DutchUser** [comment]
and i can not see an clear fix to this issue on #11

**Comment by gvlfm78** [comment]
What was the first version of OCM you installed?

**Comment by DutchUser** [comment]
I dont know witch version it is. Its atleast not higher then "OldCombatMechanics 1.0.3
" I have now the plugin multple days in the server with the false settings. But still a few players have this issue. (Not cooldown on everything)

**Comment by gvlfm78** [comment]
So do you still have the plugin installed, and what version?

**Comment by DutchUser** [comment]
Yes. I just checked it and it seems that we have version 1.10.2, I though we had the lastest version. My admin told me that -,- So i updated it to the lastest now(1.1.0) and it seem te be fixed by atleast 1 of those players. I am sorry. I am going talk to my admin about that he need to check more times.

**Comment by DutchUser** [comment]
**Reason for this thread: An admin that was to lazy to check more times.**

So this have **nothing** todo with the plugin! :)

**Comment by gvlfm78** [comment]
Very well. Also if you still have problems with some players coming online and not having their attack speed correct you may have to run once [OCMFixer](https://github.com/Rayzr522/OCMFixer)
