### ISSUE TITLE
NPE on PotionSplashEvent

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#220]
## Info

- Server version: paper spigot 1.12.2
- OldCombatMechanics version:  v1.7.0
- Server log file: 
download and open with notepad++
https://drive.google.com/open?id=1VJ6oIPgeDOZS5IGnNngIG7mP18Tx9Age
- OldCombatMechanics config file: 
download
https://drive.google.com/open?id=1gZyQw6I3jLrhA0rxXbGTYGRlMYR8DUFK

## Problem Description
problem in title of this issue, i need to remove old config and create new?
>

**Comment by gvlfm78** [comment]
It would be a good idea to try out the [latest test version](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/lastSuccessfulBuild/) and see if the issue is still present.

**Comment by leoncp9** [comment]
oook

**Comment by leoncp9** [comment]
today, 23.08.2018 with build **#57** latest version of plugin, i get this error again ERROR Could not pass event PotionSplashEvent to OldCombatMechanics v1.7.0

**Comment by gvlfm78** [comment]
@leoncp9 What kind of potion are you holding/using when this error occurs?

**Comment by gvlfm78** [comment]
@leoncp9 Also can you get the error log again but with the new version?

**Comment by gvlfm78** [comment]
@leoncp9 This issue should now be fixed in [test build 58](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/58/). Please try the new build.

**Comment by leoncp9** [comment]
ok thank, but i can't try it because my server is offline for work, i will try it

**Comment by gvlfm78** [comment]
@leoncp9 Any news?

**Comment by leoncp9** [comment]
OldCombatMechanics#58
where is the jenkins dev download web page?

**Comment by I-Al-Istannen** [comment]
The butler icon at the bottom of the readme (points to [here](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/))

**Comment by leoncp9** [comment]
thank

**Comment by gvlfm78** [comment]
@leoncp9 Do you still get this issue?

**Comment by leoncp9** [comment]
fixed
