### ISSUE TITLE
Mobs are invisible after installing plugin

### ISSUE THREAD

**Issue by DivineDestiny** [gvlfm78/BukkitOldCombatMechanics#223]
## Info

- Server version:  1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file: N/A
- OldCombatMechanics config file: https://pastebin.com/BzNSAmHR 

## Problem Description
> After installing the plugins, mob spawned from spawn eggs are all invisible. 
https://cdn.discordapp.com/attachments/475868272303145000/478887271307804672/2018-08-14_19-26-42.mp4 -Video on issue
I tried messing with the config, everything but it doesn't seem to help at all.
Once I remove OCM the mobs are all visible again.

**Comment by Rayzr522** [comment]
The mobs don't look very invisible to me, I see a bunch of wolves. What am I *supposed* to be seeing? And since there are clearly *some* mobs visible (the wolves), which mobs are not visible? Is it only hostile mobs?

**Comment by DivineDestiny** [comment]
Only hostile mobs are invisible. The wolves are there to kill the skeleton. The wolves were able to kill the skeleton and you can see the drops, but the skeleton itself is invisible.

**Comment by Rayzr522** [comment]
Hmmmm. Needless to say, in all our testing that never occured. What other plugins do you have installed?

**Comment by DivineDestiny** [comment]
The issue resolved itself. All the hostile mobs are suddenly visible again. Thanks for the support!

**Comment by Rayzr522** [comment]
Strange, please let us know if this occurs again.
