### ISSUE TITLE
Could not pass event PlayerItemConsumeEvent

### ISSUE THREAD

**Issue by AfkF24** [gvlfm78/BukkitOldCombatMechanics#225]
Another little error, was being spammed quite a bit. https://pastebin.com/raw/m3HUCr90

- Server version: Paper 1.12.2-b1550
- OldCombatMechanics version: 1.7.0-b57

**Comment by AfkF24** [comment]
Not quite sure, as it happened to a random player and I just managed to spot the error while going through some logs. Don't have much info on this.

**Comment by gvlfm78** [comment]
@AfkF24 This issue should now be fixed in [test build 58](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/58/). Please try the new build.

**Comment by AfkF24** [comment]
Yup, seems to be fixed. Thanks!
