### ISSUE TITLE
Hackers throws "potion of dealth"

### ISSUE THREAD

**Issue by Terrifical** [gvlfm78/BukkitOldCombatMechanics#227]
Server ver: 1.11.2
Error:  https://pastebin.com/62Wb0ixD

**Comment by Rayzr522** [comment]
What do you mean "potion of death"? What is actually happening? And how did they get this potion?

**Comment by HairyDragonBeck** [comment]
They get it from a hack called ‘Brewing Stand’ and they make a potion called ‘Splash Potion of Instant Damage II’ YeEt

**Comment by gvlfm78** [comment]
@Rayzr522 I believe he means potion of damage. This issue is a duplicate of #220
