### ISSUE TITLE
16 is not the minimum for no cooldown?

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#23]
I noticed the default was changed here.
https://github.com/gvlfm78/BukkitOldCombatMechanics/commit/756ea430e74e9fd9fd874ab949136e4da727dd9e#diff-ee97532d2d40af21fc87a8fc24cd37c3R29

From my testing with OCM dev 29 on Spigot 1.11, with the attack indicator enabled on the crosshair, 16 attack speed still shows an attack indicator when switching weapons and click attacking. Although it is fast, a minimum of 23 is needed for there to be absolutely no indicator, 24 for safe measures I'd say.

**Comment by gvlfm78** [comment]
I remember reading somewhere that 16 was the minimum for there to be no  attack delay. I guess that didn't include not having the indicator. I'll see about changing it

**Comment by Rayzr522** [comment]
I always see an indicator when switching tools, even at 1024. I don't believe that can be avoided. As for seeing an indicator when attacking, I don't know about that.

**Comment by mibby** [comment]
>I always see an indicator when switching tools, even at 1024. I don't believe that can be avoided. 

That's odd because on 1.11, I don't see an indicator when switching weapons or attacking with values 23 and over. Could be a new thing with 1.11. But from my quick testing, you need a value of at least 23 to see no indicator / swing fill bar whatsoever when attacking.

**Comment by gvlfm78** [comment]
I can confirm that in 1.11 a value of 16 or above still shows the indicator.

**Comment by mibby** [comment]
Closed why? :( A value of 16 shows the attack indicator bar when swinging on 1.11. Thus it would have a slight cooldown since it isn't instantly negated at that value. The attack indicator is present all the way up to a value of 23. 23 and above, no indicator shows whatsoever when swinging a sword. Only when swapping between items in your hot-bar for a fraction of a second.

I'm not sure why you are able to confirm it still shows the indicator, but it doesn't for me in my testing. Unless your testing environment isn't properly 1.11 or you forgot to reload the config after making a change.

**Comment by gvlfm78** [comment]
Wait is this bug report about the indicator while switching items or attacking? You never specified. I checked the item switching.

**Comment by mibby** [comment]
With attacking. The indicator seems to show up regardless when you scroll through your items in your hot-bar (although micro-second flashing with a higher value). But you can get it to not show up anymore when swinging with a value of 23 or higher. I settled on 24 since it is a nicer number.

**Comment by mibby** [comment]
May want to change the language here too.  16> 24 https://github.com/gvlfm78/BukkitOldCombatMechanics/blob/master/src/main/resources/config.yml#L28
