### ISSUE TITLE
NPE in Sword Blocking module

### ISSUE THREAD

**Issue by yanisssch** [gvlfm78/BukkitOldCombatMechanics#232]
## Info

- Server version: spigot 1.9.4
- OldCombatMechanics version: 1.6.6
- Server log file: https://pastebin.com/P6rhZuH1
- OldCombatMechanics config file: https://pastebin.com/eC8hg7wj

## Problem Description
> this error cause lag on my server and i don't know why this error happened

**Comment by I-Al-Istannen** [comment]
Can you try a recent dev build from [here](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/)?

**Comment by yanisssch** [comment]
> 
> 
> Can you try a recent dev build from [here](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/)?

now i have this error -_-

https://pastebin.com/dh2Mwww6

**Comment by I-Al-Istannen** [comment]
@yanisssch Can you try the newest dev build from [here](http://ci.rayzr.tech/job/OldCombatMechanics/17/)?
