### ISSUE TITLE
PlayerJoinEvent packet_handler missing

### ISSUE THREAD

**Issue by Twiistrz** [gvlfm78/BukkitOldCombatMechanics#234]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 
- Server log file: https://hastebin.com/irorasulay.rb
- OldCombatMechanics config file: https://hastebin.com/kicavayodo.bash

## Problem Description
> Could not pass event PlayerJoinEvent to OldCombatMechanics

**Comment by I-Al-Istannen** [comment]
Likely a duplicate of #211.

Can you try a more recent dev build from the [jenkins instance](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/)?

**Comment by gvlfm78** [comment]
@Twiistrz so do you still get this issue with a newer test build?

**Comment by Twiistrz** [comment]
@gvlfm78 Not anymore thank you :+1:
