### ISSUE TITLE
playerWeakReference is null

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#235]
[20:30:28 WARN]: [OldCombatMechanics] playerWeakReference or its value is null. This should NOT happen at this stage.Please report the error on github. (write@1320504165)

>

**Comment by leoncp9** [comment]
version latest, server paper spigot 1.12.2

**Comment by gvlfm78** [comment]
What exact version of the plugin do you have? Is it the latest from Spigot?

**Comment by Rayzr522** [comment]
Please try the [latest dev build](http://ci.rayzr.tech/job/OldCombatMechanics/19/) and let us know if this is still an issue.

**Comment by gvlfm78** [comment]
Issue now tracked on #248 for the newest development build.
