### ISSUE TITLE
Custom messages.

### ISSUE THREAD

**Issue by TheIntelloBox** [gvlfm78/BukkitOldCombatMechanics#24]
Hello,

Could you add custom messages when we kill a mob, etc ?

Thanks ! :D

**Comment by Rayzr522** [comment]
Kill a mob? Why?

**Comment by TheIntelloBox** [comment]
When we kill an entity it's says : "Spider took 5 damage. 11/16 Health".

**Comment by Rayzr522** [comment]
Ok then xD

**Comment by TheIntelloBox** [comment]
xD.
