### ISSUE TITLE
"playerWeakReference or its value is null. This should NOT happen at this stage"

### ISSUE THREAD

**Issue by xDacon** [gvlfm78/BukkitOldCombatMechanics#242]
## Info

- Server version:  Paper 1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file: https://pastebin.com/raw/EcaUT5CW
- OldCombatMechanics config file: https://pastebin.com/raw/jbFjEX5G

## Problem Description
> Server gets spammed with error above and locks up server

**Comment by gvlfm78** [comment]
Issue now tracked on #248 for the latest development version.
