### ISSUE TITLE
Unable to find method getTypeId

### ISSUE THREAD

**Issue by boss89** [gvlfm78/BukkitOldCombatMechanics#245]
## Info

- Server version: spigot 1.13.1
- OldCombatMechanics version: 1.6.6
- Server log file: https://hastebin.com/loyemucona.md
- OldCombatMechanics config file: https://hastebin.com/kiboriwaze.bash

## Problem Description
> 
keep getting errors in server log, [Server thread/ERROR]: Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6

**Comment by I-Al-Istannen** [comment]
Duplicate of #246 and likely #229.
