### ISSUE TITLE
NameTagEdit Incompatibility

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#247]
## Info

- Server version: 
- OldCombatMechanics version: Compilazione #20 (5-ott-2018 20.24.08) 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> the conflict is between nametagedit and OldCombatMechanics, if use OldCombatMechanics on my server, i can't see my owne nametag on TAB, without i can see it
i use thi plugin on my bedwars server with leafbedwars

**Comment by I-Al-Istannen** [comment]
### Can't reproduce:

Viewing as another user:
![grafik](https://user-images.githubusercontent.com/20284688/47270990-ce115d80-d573-11e8-8135-259df6e32c18.png)

Viewing as the same user:
![grafik](https://user-images.githubusercontent.com/20284688/47270995-dbc6e300-d573-11e8-89d2-dc1958ab19c9.png)

**Comment by Rayzr522** [comment]
Which exact NameTagEdit plugin are you using, @leoncp9?

**Comment by leoncp9** [comment]
https://www.spigotmc.org/resources/nametagedit.3836/

**Comment by I-Al-Istannen** [comment]
That is the plugin I tried too.
```
$ sha256sum ~/Downloads/NametagEdit.jar general_storage/Minecraft/Servers/1.13.1/plugins/NametagEdit.jar
4680b8778e3e0350f9713d3206ca30fe452b38f5932e524d1d1906a6b2a2a55b  /home/i_al_istannen/Downloads/NametagEdit.jar
4680b8778e3e0350f9713d3206ca30fe452b38f5932e524d1d1906a6b2a2a55b  general_storage/Minecraft/Servers/1.13.1/plugins/NametagEdit.jar
```

Could you try it too @Rayzr522 and can you @leoncp9 post your OCM and nametagedit config?

**Comment by Drc-DEV** [comment]
Just disable the "Collisions" feature in OCM and use the no collisions built in NameTagEdit to avoid incompatibility.
