### ISSUE TITLE
Armor Bug when wearing the items

### ISSUE THREAD

**Issue by Cabooost** [gvlfm78/BukkitOldCombatMechanics#25]
After wearing any piece of armor using the RightClick feature from the hotbar, the armor gets glitched.
Just a text glitch from my testing, but may add lots of confusion to players.

Glitch: (Have F3+H enabled to see item values such as Armor and Toughness)

Any Chestplate, for example a diamond one, has +2 Armor Toughness and +8 Armor.
The second you wear the diamond chestplate, it will turn its stats into +9999 Armor Toughness and +8 Armor. This happens to any piece of armor that is worn via RightClicking from the hotbar.

![2016-11-28_20 38 20](https://cloud.githubusercontent.com/assets/8120668/20696808/a955efa0-b5aa-11e6-9559-88868477be18.png)

![2016-11-28_20 38 22](https://cloud.githubusercontent.com/assets/8120668/20696809/a95675b0-b5aa-11e6-8ab3-01bac6618f70.png)

**Comment by Rayzr522** [comment]
This is not a bug. It's the only way to make the armor module work, it's quite a bit of hackery... they certainly don't like to make it easy for us :wink:

@gvlfm78 had to come up with a way to calculate accurate armor levels, and if I remember correctly the armor toughness factor was causing problems, so we basically eliminated it by always setting it to 9999. Correct me if I'm wrong, @gvlfm78 :grin:

**Comment by gvlfm78** [comment]
Yeah it's as @Rayzr522 said, you can check out the [spreadsheet here](https://docs.google.com/spreadsheets/d/1R_t09oCt-5soYEBgYnbbJHuEtDYa1jIsml41s7FpUrc/edit#gid=1273544302) with how I calculated the damage
