### ISSUE TITLE
Error in console - Possibly config error

### ISSUE THREAD

**Issue by LazyDkk** [gvlfm78/BukkitOldCombatMechanics#254]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.6
- OldCombatMechanics config file: 
https://pastebin.com/djA7BP6M
- Console Error: 
https://pastebin.com/5sfbexPQ

## Problem Description
> Right when the server starts, this error occurs. I've tried to figure out why but so far, I haven't been able to. I hope to get some help here, thank you.

**Comment by gvlfm78** [comment]
@LazyDkk Please try the latest test build from [here](http://ci.rayzr.tech/job/OldCombatMechanics/), as many issues have already been fixed in it.

**Comment by gvlfm78** [comment]
Also, this appears to be a duplicate of #215 , which should now be fixed.
