### ISSUE TITLE
Packets Error

### ISSUE THREAD

**Issue by ZoneTriplu** [gvlfm78/BukkitOldCombatMechanics#257]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.7.0
- Server log file: https://pastebin.com/VG8J8ea4
- OldCombatMechanics config file: https://pastebin.com/tg0vPS5Y

## Problem Description
All players from my server get kicked.

**Comment by gvlfm78** [comment]
@Rayzr522 @I-Al-Istannen does this have to do with the reflective methods in the no-collisions module?

**Comment by I-Al-Istannen** [comment]
Sorry, I was a bit busy the last few days.

It is an error in a packet listener.
But that error says that the player field was null in a packet, which I don't think a normal server sends (at least no server I tried did that and *it makes no sense at all to do it*).

But the exception is caught and **should not kick the players**:
In fact, I just tried it and threw the NPE myself --- nobody was kicked. I suspect that another plugin might not handle the corrupted packet that is being sent correctly.

I could say a bit more if the server had debug mode enabled in the `server.properties` @ZoneTriplu.

**Comment by ZoneTriplu** [comment]
i'll enable

**Comment by ZoneTriplu** [comment]
It's possible from ProtocolSupport?

**Comment by ZoneTriplu** [comment]
https://hastebin.com/exirurumak.rb that's with debug mode

**Comment by I-Al-Istannen** [comment]
The debug mode from the server properties? If so, is that the full output you get?
Also, can you link the protocol support plugin you use?

**Comment by ZoneTriplu** [comment]
Yes that's all...

În vin., 21 dec. 2018, 23:49 I-Al-Istannen <notifications@github.com a
scris:

**Comment by I-Al-Istannen** [comment]
Could reproduce it once randomly and then never again, but I have an idea of the cause.

Can you see if the attached version works? Also, do you have any way to consistently reproduce it?

[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2705422/OCM.zip)

**Comment by I-Al-Istannen** [comment]
@Tigerpanzer02 Regular spigot? Does it happen when a player instantly leaves again after joining?

**Comment by Tigerpanzer02** [comment]
Yes regular spigot

Don´t know if it only on fast leaves. I will have a look on console when it will throw again

**Comment by gvlfm78** [comment]
@Tigerpanzer02 @ZoneTriplu Is this issue still present in the [latest test version](https://ci.rayzr.dev/job/OldCombatMechanics/) of OCM?
