### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Rajsingh31** [gvlfm78/BukkitOldCombatMechanics#260]
## Info

- Server version: 1.12
- OldCombatMechanics version: Latest
- Server log file: 
- OldCombatMechanics config file: Update

## Problem Description
> Less an issue, more a question. When will it be updated to 1.13

**Comment by gvlfm78** [comment]
Duplicate of #204 . Please use [test builds](http://ci.rayzr.tech/job/OldCombatMechanics/) for 1.13 compatibility.
