### ISSUE TITLE
Can't remove mechanics

### ISSUE THREAD

**Issue by JoeProKill2000** [gvlfm78/BukkitOldCombatMechanics#267]
I downloaded your plugin, liked it, but changed my mind. I deleted the jar and folder, but now, 1.12 mechanics wont come back! I can still hit them like im in 1.8 just mobs take knockback now. I want to remove the mechanics. Please help.

**Comment by Rayzr522** [comment]
Is it just you, or is it all players on your server? Additionally, what version of OldCombatMechanics did you have installed previously?

**Comment by JoeProKill2000** [comment]
I installed the latest (1.6.6) and for some reason... just me. But I dont want 1.12 mechanics either.

**Comment by Rayzr522** [comment]
Of course, understandable. Please stop your server, reinstall OldComabtMechanics, log back in and out again, stop the server again, and uninstall it. It resets your combat when you log out, so that should solve your issue.

**Comment by JoeProKill2000** [comment]
It worked! Thanks :)

**Comment by Rayzr522** [comment]
No problem, glad to help! I'm going to close this issue now, but please feel free to open a new issue if you have any further problems. 

Have a nice day! :)
