### ISSUE TITLE
/ocm reload duplicate recipe ignored

### ISSUE THREAD

**Issue by odie8800** [gvlfm78/BukkitOldCombatMechanics#271]
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 1.6.6
- Server log file: https://gyazo.com/5c2368fa6a81fb0fd3dd87673e5294cc
- OldCombatMechanics config file: https://pastebin.com/bjAAg1ag

## Problem Description
> Everytime I do /ocm reload, it shows internal error has occured. Is this a developmental error or is there something wrong within my config file?

**Comment by gvlfm78** [comment]
Please try the latest development build from [here](https://ci.rayzr.tech/job/OldCombatMechanics/) and tell us if the issue is still present.
