### ISSUE TITLE
Error on Console

### ISSUE THREAD

**Issue by PinoyLifeCraft** [gvlfm78/BukkitOldCombatMechanics#273]
## Info

- Server version: 1.13.2
- OldCombatMechanics version: 1.6.6

## Problem Description
> 
 Error in console. https://pastebin.com/WzjfSYNN

**Comment by gvlfm78** [comment]
Duplicate of #249 #246 #245 #253 #266 #269. Please use the latest test build of OldCombatMechanics from [here](http://ci.rayzr.tech/job/OldCombatMechanics/).
