### ISSUE TITLE
Sword-Block problem

### ISSUE THREAD

**Issue by Berciu** [gvlfm78/BukkitOldCombatMechanics#275]
## Info

- Server version: Paperclip 1.12.2
- OldCombatMechanics version: Latest src github
- Server log file: https://pastebin.com/J4NcgWsD
- OldCombatMechanics config file: https://pastebin.com/GMaR1WWi

## Problem Description
> If the sword-block is on, players jump from a height with the sword locked looking down and holding the S key does not die
I apologize for my English, I come from another country

**Comment by gvlfm78** [comment]
There is no relevant error in the server log. I don't understand what issue you're having but you should first try to update to a newer [test version](https://ci.rayzr.tech/job/OldCombatMechanics/).
