### ISSUE TITLE
ARMOUR not applicable

### ISSUE THREAD

**Issue by Leomelonseeds** [gvlfm78/BukkitOldCombatMechanics#276]
This is spamming the console:

https://gyazo.com/d4cc58ece9c128bc8b0d7475c561d877

I am using the latest dev build from the jenkins website.

**Comment by LoXR** [comment]
Getting this aswell
Paper 1.13 Latest Dev version.

**Comment by darksaid98** [comment]
I can confirm I get this as well using Paper #522, https://pastebin.com/7DF7HP30
Setting old-armour-strength enabled to false stops the error from occuring.

**Comment by gvlfm78** [comment]
@Leomelonseeds @LoXR @darksaid98 Sorry lads, it appears this may be a very simple fix. Can you try [test version 33](https://ci.rayzr.tech/job/OldCombatMechanics/33/) or greater?

**Comment by darksaid98** [comment]
I can confirm I get no errors anymore with the setting, enabled running the latest dev build#33 & paper 525. Thanks for the patch =)
