### ISSUE TITLE
Citizen NPCs movable with fishing rods

### ISSUE THREAD

**Issue by Tomographix** [gvlfm78/BukkitOldCombatMechanics#278]
## Info

- Server version: 1.13 - PaperSpigot
- OldCombatMechanics version: 1.7.0
- Server log file: N/A
- OldCombatMechanics config file: https://pastebin.com/8YhKrq7y

## Problem Description
> Citizen NPC's can be moved around with fishing rods. Without OldCombatMechanics on this cannot happen. Is quite annoying as people constantly move around the NPCs.

**Comment by Tomographix** [comment]
Hi, any update at all? Thanks :)

**Comment by I-Al-Istannen** [comment]
Citizens are implemented as real CraftPlayers apparently, so the plugin treats them as such. It would need to be special cased for citizens.

That might also be needed in a few other places, not sure. @gvlfm78 Do you know of anything that breaks if an NPC interacts with it (apart from fishing)?

**Comment by gvlfm78** [comment]
@I-Al-Istannen I'm not entirely sure what you mean by that question but probably not?

**Comment by I-Al-Istannen** [comment]
Can you try this version here (unzip the zip):
[OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2984605/OCM.zip)

@Tomographix

**Comment by Tomographix** [comment]
> Can you try this version here (unzip the zip):
> [OCM.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2984605/OCM.zip)
> 
> @Tomographix

Seems to work so far, will keep you updated. Thanks so much.
