### ISSUE TITLE
EntityDamageByEntityEvent to OldCombatMechanics v1.7.0

### ISSUE THREAD

**Issue by BurakDorman** [gvlfm78/BukkitOldCombatMechanics#281]
- Server version:  1.12.2 Spigot
- OldCombatMechanics version:  1.7.0
- Server log file: https://pastebin.com/JF7jiRE3
- OldCombatMechanics config file: https://pastebin.com/eU27GzF7

## Problem Description
> EntityDamageByEntityEvent to OldCombatMechanics v1.7.0 Error on start up.

**Comment by gvlfm78** [comment]
Duplicate of #276
