### ISSUE TITLE
Old Golden Apples module overrides superior effects

### ISSUE THREAD

**Issue by Drc-DEV** [gvlfm78/BukkitOldCombatMechanics#283]
## Info
- Server version: 1.12.2 PaperSpigot
- OldCombatMechanics version: 1.6.6

## Problem Description
>  If a player has a superior effect, for example Resistance II, when he eats an enchanted golden apple (configured with Resistance I) he gets downgraded to Resistance I. This should not happen, you should check for pre-existing effects and not apply inferior ones if they are present!

Snippet for a better method of handling this: https://pastebin.com/uaTDVnkL

**Comment by gvlfm78** [comment]
Hold on, I don't remember right now but can you check whether this issue is still present in the [newest test versions](https://ci.rayzr.tech/job/OldCombatMechanics/)?

**Comment by Drc-DEV** [comment]
I checked in the source code on this github. So if the dev versions are just this source compiled, the bug is present.

**Comment by VaiTon** [comment]
The check should be already be performed on https://github.com/gvlfm78/BukkitOldCombatMechanics/blob/7d1d87255a3d32beead1a041aaa49f263fdcb0c8/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleGoldenApple.java#L177
