### ISSUE TITLE
Uninstall cooldown still disabled

### ISSUE THREAD

**Issue by ender1324** [gvlfm78/BukkitOldCombatMechanics#284]
Hello,
I deleted oldcombatmechanics **BUT** when I restarted the sevrer after deletion the cooldown timer was still not there... I tried OCMfixer, didnt work...
version of the server: 1.13.2 R0.1
plugin version: 1.6.6

**Comment by gvlfm78** [comment]
How many players are affected?

**Comment by ender1324** [comment]
4 players out of 4

**Comment by gvlfm78** [comment]
Please follow these steps:

* Shut down the server
* Reinstall OCM
* Start the server
* Have everyone log in
* Have everyone log out
* Shut down the server
* Remove the OCM jar
* Restart the server
* Verify if the players are still having issues with the attack speed

**Comment by ender1324** [comment]
Yep that worked, thanks
