### ISSUE TITLE
Async hit detection

### ISSUE THREAD

**Issue by Gracv** [gvlfm78/BukkitOldCombatMechanics#287]
How about add compatibility with this plugin? [https://www.spigotmc.org/resources/smashhit-async-hit-detection.36835/](url) Would be nice.

**Comment by I-Al-Istannen** [comment]
What doesn't work currently?

**Comment by gvlfm78** [comment]
Is this related to issue #19?

**Comment by Gracv** [comment]
Other plugin caused problems. Sorry.
