### ISSUE TITLE
Additional configurable PVP options.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#29]
I was wondering if a few additional pvp tweaking options could be implemented in OCM. Primarily to avoid having to use multiple separate plugins to modify, tweak, and handle combat in 1.9+. Similarly to my last suggestion with having a configurable attack frequency / async hit detection (https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/19), these additional suggestions would be coming from a plugin called PrimoCombat.

https://github.com/PrimoMC/PrimoCombat

- Having the option to disable random projectile trajectories.
- Having an option to disable bow boosting.
- Having an option to prevent using a bow in your offhand.

**Comment by gvlfm78** [comment]
Is the white/blacklist feature I just added for the disable-offhand module good enough for preventing bow in the offhand?

**Comment by gvlfm78** [comment]
Sorry @mibby the Jenkins server was down for a bit but it is now back up. [This](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/39/) is the test build I was talking about

**Comment by gvlfm78** [comment]
Well @mibby I have now added these features in [this test build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/42/)
