### ISSUE TITLE
PlayerJoinEvent & PlayerQuitEvent

### ISSUE THREAD

**Issue by Nikwitz** [gvlfm78/BukkitOldCombatMechanics#292]
## Info

- Server version: Paper 1.13.2
- OldCombatMechanics version: 1.6.6
- Server log file: https://hastebin.com/ozelejukep.md
- OldCombatMechanics config file: https://hastebin.com/bitohefimu.bash

## Problem Description
> When people join and leave the server some errors pop up in the console. I do not know if there is any fix for this but it is spamming my console when I have ~30 players online. Hopefully you can help me. If there is anything else you need, just ask.

Plugins: AuctionHouse, BuyCraftX, ChestShop, Citizens 2, Clearlag, CombatLogX, CoreProtect, CrateReloaded (Premium), DGSCOnTime (Own plugin), DGSCXray (Own plugin), EnchantControl, EssentialsX, EssentialsXChat, EssentialsXSpawn, FeatherBoard, HolographicDisplays, JobsReborn, Litebans, LuckPerms, mcMMo, MendingFishBlock (Own plugin), Multiverse Core, Multiverse Portals, MVdWPlaceholderAPI, NightVision, NuVotifier, OldCombatMechanics, PlayerVaultsX, ProtocolLib, Quests, ShopGUIPlus, Skript, Spartan, SuperVanish, Tab, TokenManager, Towny, TownyChat, TownyNameUpdater, Vault, VotingPlugin, Websend, WorldBorder, WorldEdit, WorldGuard and WorldGuardExtraFlags.

**Comment by gvlfm78** [comment]
Please update to the [latest test version](https://ci.rayzr.dev/job/OldCombatMechanics/) of the plugin.
