### ISSUE TITLE
Custom shield damage reduction with arrows

### ISSUE THREAD

**Issue by uiytt** [gvlfm78/BukkitOldCombatMechanics#294]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.6.6
- OldCombatMechanics config file: 25

## Problem Description
> I was wondering if there is any way to allow shield to block all arrow but set the blockage damage reduction to 50%

**Comment by uiytt** [comment]
Yes please ^^

**Comment by gvlfm78** [comment]
As far as I remember, the issue with having this feature was that there wasn't a proper way to know when a player blocked an arrow, and the damage they would have received (unless I missed something or something changed in the meantime).

**Comment by uiytt** [comment]
Maybe add an option to let the shield as normal, like a boolean ?

**Comment by gvlfm78** [comment]
There is now an option in version 1.7.1 to configure shields' damage reduction when hit by projectiles separately from normal damage. If that is not what this issue entailed, please open a new one.
