### ISSUE TITLE
Slow Fall & Turtle Master potions causing errors

### ISSUE THREAD

**Issue by Ferocimo** [gvlfm78/BukkitOldCombatMechanics#303]
Hello,

In latest versions of the plugin the slow fall potion is not implemented in config. This causes the following error in console : 
https://pastebin.com/cNuZhf0E

And the potion is undrinkable while the plugin is active.

Thank you for looking into this.

**Comment by gvlfm78** [comment]
Support for Slow Falling and Turtle Master potions should now be present since commit b45d8be.

**Comment by Ferocimo** [comment]
Slow fall works, Turtle Master doesn't give the correct effects (doesn't give Resistance, and power of Slowness is incorrect).

**Comment by gvlfm78** [comment]
Please check with commit da859cb, I added support for the Luck potion but removed that for Turtle Master, as Bukkit doesn't seem to return all the effects for the potion. However, this means it should now work as normal in 1.13.

**Comment by Ferocimo** [comment]
It works now, thank you.
