### ISSUE TITLE
Off-hand item disappearing when drinking potion

### ISSUE THREAD

**Issue by Ferocimo** [gvlfm78/BukkitOldCombatMechanics#304]
Hello,

In latest versions of the plugin, on Minecraft 1.13, if you drink a potion while having something held off hand, that thing will disappear and be replaced by an empty bottle (you need to be in survival to reproduce this bug).

Thank you for looking into this as soon as possible, since because of this issue we are forced to use older versions of OCM.

**Comment by gvlfm78** [comment]
Commit 69f2a99 should fix this issue, please check

**Comment by Ferocimo** [comment]
It works fine, thank you.
