### ISSUE TITLE
Hitting cooldown doesn't turn back on for me

### ISSUE THREAD

**Issue by Kiluminator** [gvlfm78/BukkitOldCombatMechanics#305]
- Server version: 1.13.2
- OldCombatMechanics version: 1.7.1
- OldCombatMechanics config file: https://pastebin.com/ZS0JpxW7

I don't want the plugin to do anything but make fishing rods work like they did earlier. Therefore I disabled everything except that in the config but the attacking cooldown doesn't come back for me. This occured once I updated from the last version to 1.7.1. Before that I had normal 1.13 attacking cooldowns, then after updating I had to disable anything in the config again and now the attack delay doesn't come back for me. Everyone else is not affected, so they have the delay they way I want them to. I have tried reconnecting, reloading, restarting the server.

**Comment by gvlfm78** [comment]
Please make sure you:
* have everyone affected log into the server with the attack cooldown module enabled;
* have them all log out;
* shutdown the server;
* disable the attack cooldown module;
* start the server again.
