### ISSUE TITLE
How do you enable offhand? I've seen the other people writing about it but i cant find the whitelist and therefore not how to remove it

### ISSUE THREAD

**Issue by Sumsar9876** [gvlfm78/BukkitOldCombatMechanics#306]
## Info

- Server version: 
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
>

**Comment by gvlfm78** [comment]
Turn the `disable-offhand` module to `enabled: false` in the config.yml file.
