### ISSUE TITLE
Plugin still active after deletion

### ISSUE THREAD

**Issue by JustKavis** [gvlfm78/BukkitOldCombatMechanics#311]
At first I had the plugin installed, but due to other reasons, I concluded it was the best specifically for this server to not have the 1.8 combat system...

I deleted everything, but the system is still present?

**Comment by JustKavis** [comment]
So in a way I'm even more concerned, I read another thread of this happening, and they were instructed to, re-install it, have players log in and log out, then un-install it. I did this on my own, and it worked, but when other players who didn't do this still had this issue of them still swinging around with no cool-down.

And I can definitely NOT have ALL players at once come in for a bit, and have them do this since all of them have different times when they're available. 

I'm hoping that there is another way that is not that, or deleting playerdata since that is a definitely a no-go either.  If there isn't I think this plugin just threw off the balance of PvP & PvE.

**Comment by Rayzr522** [comment]
Please try https://github.com/Rayzr522/OCMFixer. It should fix your issue. I would recommend making a backup first just in case, but it's been a reliable fix for users in the past.

**Comment by gvlfm78** [comment]
> At first I had the plugin installed, but due to other reasons, I concluded it was the best specifically for this server to not have the 1.8 combat system...
> 
> I deleted everything, but the system is still present?

May I know what **deleted everything** means? This shouldn't normally happen.

**Comment by Rayzr522** [comment]
^ we would love to know why this keeps happening, any information you can give would be great. However, I also just released an update with a bunch of bug fixes for OCMFixer today, so make sure you get the latest version whenever you test it (which is now 1.4.1).

**Comment by JustKavis** [comment]
Hey!

So I did try the OCMFixer, it worked for most except one oddly enough? And by everything I mean I deleted the .jar and the folder.

I would have to try the newest version of the OCM fixer, I will let you know once I do.

**Comment by gvlfm78** [comment]
@JustKavis Did you stop the server before removing the jar?

**Comment by gvlfm78** [comment]
@JustKavis any update?

**Comment by blazegod10** [comment]
I removed the folder and the jar and it is still stuck on 1.8 combat
Server was stopped and I removed both and it did not fix

**Comment by Rayzr522** [comment]
@blazegod10 please use [OCMFixer](https://github.com/Rayzr522/OCMFixer) to resolve this issue. What version of OCM were you using before removing it?

**Comment by blazegod10** [comment]
Where do i put OCMFixer?

**Comment by Rayzr522** [comment]
It is a plugin, you can download the JAR from the releases tab on that page. (or just click [here](https://github.com/Rayzr522/OCMFixer/releases))

**Comment by blazegod10** [comment]
That worked, Thanks so much man!

**Comment by Rayzr522** [comment]
I am going to close this issue for now as we still have not heard from the OP in over a month. @JustKavis, please re-open this if you have any further issues.
