### ISSUE TITLE
Stack of potions are not consumed when drank

### ISSUE THREAD

**Issue by Ferocimo** [gvlfm78/BukkitOldCombatMechanics#315]
- Server version: Paper version git-Paper-628 MC 1.13.2
- OldCombatMechanics version: 1.7.36-BETA
- OldCombatMechanics config file: "old potion effects" set to TRUE.

Hello,

If old potion effects module is enabled, stacks of potions can be drank without them being consumed at all. So you have infinite amount of potions. This is noticeably an issue with Mobarena which gives stacks of potions.

Thank you for looking into this as soon as you can, since it's kinda breaking our server right now.

**Comment by gvlfm78** [comment]
@Ferocimo please try [test build 53](https://ci.rayzr.dev/job/OldCombatMechanics/53/).

**Comment by Ferocimo** [comment]
@gvlfm78 Fixed, thank you.
