### ISSUE TITLE
1.14 support?

### ISSUE THREAD

**Issue by AstralForce** [gvlfm78/BukkitOldCombatMechanics#316]
## Info

- Server version: 1.14.2
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
>  I plan to update my server to 1.14.2 soon and I have absolutely loved this plugin! I wanted to know if this plugin is going to be updated to work for 1.14.2. Thank you for your time!

**Comment by gvlfm78** [comment]
I don't see any reason why it shouldn't work. If you encounter any issues you can open a new ticket for it.
