### ISSUE TITLE
Slow fall potions can't be drank

### ISSUE THREAD

**Issue by Ferocimo** [gvlfm78/BukkitOldCombatMechanics#318]
Server version: Paper version git-Paper-628 MC 1.13.2
    OldCombatMechanics version: 1.7.36-BETA
    OldCombatMechanics config file: "old potion effects" set to TRUE.

Hello,

If old potion effects module is enabled, slow-falling potions can't be drank (it applies the effect which immiadetely fades away).

Thank you for looking into this.

**Comment by northerncarrots** [comment]
This can be fixed by adding an extended timer to the potion effect:

```    slow_falling:
      drinkable:
        base: 90
        extended: 240
      splash:
        base: 90
        extended: 240

**Comment by gvlfm78** [comment]
I somehow missed that there was an extended potion of slow falling. It has now been added to the config.yml.
