### ISSUE TITLE
Can’t uninstall plugin

### ISSUE THREAD

**Issue by BluSpectrum** [gvlfm78/BukkitOldCombatMechanics#319]
## Info
- Server version: 1.14.3
- OldCombatMechanics version: 1.7.3
- Server log file: N/A
- OldCombatMechanics config file: N/A

## Problem Description
> I simply cannot uninstall the plugin, I have deleted both the jar file and the config folder and every single feature is still in place. Even on new swords the attack damage is 21.6 and I am very frustrated at this point. Nothing has been reverted and it is slowing down my server quite a bit as well. I really need a solution to this as soon as possible.
 
Things i’ve tried:
>Deleting the plugin
>Disabling every feature then deleting the plugin
>Moving only the essential components of the server to a newly created server
>Toggling the plugin like normal

Nothing has worked. I really hope i can get this sorted out, i’m tired of this. Thanks in advance.

**Comment by gvlfm78** [comment]
Can we know exactly the steps you took before you deleted the OldCombatMechanics Jar file?

**Comment by BluSpectrum** [comment]
If you’re referring to what i did before  I started trying to delete it, all I had done was change the config file to allow elytras. The plugin was enabled for a few days, then I decided I didn’t want the plugin so I tried deleting it.
If you’re referring to the steps for deleting the plugin that’s the first thing I did to get rid of it.

**Comment by Rayzr522** [comment]
Did you uninstall the plugin via Plugman while players were still on your server?

In the meantime, please use [OCMFixer](https://github.com/Rayzr522/OCMFixer.git), it should fix your issues.

**Comment by BluSpectrum** [comment]
No, I haven’t used anything other than manually deleting it to get rid of it. I’ll try OCMFixer and let you know of the results.

**Comment by BluSpectrum** [comment]
Using OCMFixer worked really well. I’ll be sure to look into Plugman and I really appreciate the help. Thank you!

**Comment by Rayzr522** [comment]
Thanks. I just wanted to make sure you weren't using Plugman to unload it (which isn't supported, although we are adding support to ensure this doesn't happen in the future). There are still some issues we are hammering out but I'm glad OCMFixer solved your problems in the meantime.
