### ISSUE TITLE
ReAdd cooldowns

### ISSUE THREAD

**Issue by YuseiEleven** [gvlfm78/BukkitOldCombatMechanics#32]
Hello,
I installed OCM on my server, but now i want to test some plugin without him (OCM) but I can't get back the cooldown of 1.9. I have removed in my plugin folder the .jar file and the folder.

I really need to get back the cooldown (true 1.9 cooldown).

Please, could you help me?

**Comment by gvlfm78** [comment]
What version did you do this with? It's supposed to remove the cooldown when you log out/ do _/ocm reload_

**Comment by YuseiEleven** [comment]
The server is on 1.10.2, i can't do /ocm reload because i've deleted the plugin. There are 5 maps on the server and all have the same problem, all sword we craft or give or take in the creative inventory don't have cooldown.

**Comment by gvlfm78** [comment]
What version of the plugin did you have before?

How did you 'delete' the plugin? Because any normal way of removing it shouldn't cause this problem

**Comment by YuseiEleven** [comment]
it was the 1.1.0 version of the plugin. I've deleted the .jar in the server's FTP, in the plugin folder, and right click and click "delete", same with the folder OCM with the config file.

**Comment by gvlfm78** [comment]
All versions of the plugin are compatible with 1.10. I meant did you stop the server before removing the plugin or not?

**Comment by YuseiEleven** [comment]
i've first remove the plugin, then i've restart, maybe i have to readd the plugin and do /ocm disable or something like this ?

**Comment by gvlfm78** [comment]
Did you turn the server off before removing the plugin?

**Comment by YuseiEleven** [comment]
no

**Comment by gvlfm78** [comment]
May I ask how you managed to remove it then? Did you use plugman?

**Comment by YuseiEleven** [comment]
no, i removed it when the server was online, then i've stop it and restart

**Comment by gvlfm78** [comment]
Well that was your problem then. You should have either turned the server off or turned the modules off in the config then done _/ocm reload_ before removing the .jar

The way to fix it now is to use the [OCMFixer](https://github.com/Rayzr522/OCMFixer) plugin created by Rayzr522. Read carefully the instructions on the page on how to fix it. Once you've run the commands you can remove that plugin.

**Comment by YuseiEleven** [comment]
Thanks, solved. ^^
