### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by bonn2** [gvlfm78/BukkitOldCombatMechanics#323]
- Server version: Paper 1.14.4
- OldCombatMechanics version: 1.7.3
- Server log file: https://pastebin.com/T2mZLKTs
- OldCombatMechanics config file: https://pastebin.com/pgELuzxD

## Problem Description
> When hitting the ground with a sword the player stutters almost like rubberbanding. Doesn't happen with any other item

**Comment by gvlfm78** [comment]
I have never seen or heard of this behaviour with OldCombatMechanics, are you sure it is not because of some other plugin (or incompatibility between plugins)?

**Comment by bonn2** [comment]
I can check I will get it on a server all by itself and see if it happens again

**Comment by bonn2** [comment]
Hmm I can't even reproduce it now. Not sure what happened. It was definitely occouring but idk. Case closed I guess?
