### ISSUE TITLE
Fishing rod doesn't activate pressure plates

### ISSUE THREAD

**Issue by Styii** [gvlfm78/BukkitOldCombatMechanics#324]
## Info

- Server version: 1.14.3
- OldCombatMechanics version: 1.7.3
- Server log file: https://pastebin.com/mKDWm7Xr
- OldCombatMechanics config file: https://pastebin.com/MmeyFYb5

## Problem Description
>  No one is able to activate pressure plates using the fishing rod when this plugin is active. We have only tested the light pressure plate so far but it is supposed to work using a fishing rod. The fishing rod needs to activate using a fishing rod in order for a lot of my redstone contraptions to work including my auto fishing farm. I don't understand what the issue is and would appreciate some help. Thank you

**Comment by gvlfm78** [comment]
Do you mean hitting the pressure plate with a fishing rod?

**Comment by I-Al-Istannen** [comment]
@Styii 
OCM does not change the bobber entity and it seems to work for me:
![Screenshot 2019-07-27 20-32-03](https://user-images.githubusercontent.com/20284688/61998272-da4fbb80-b0ad-11e9-87b4-8c5609d20edf.png)
![Screenshot 2019-07-27 20-32-30](https://user-images.githubusercontent.com/20284688/61998273-dae85200-b0ad-11e9-8f16-d163b9c38f11.png)

Using OCM 1.7.4-Beta and Minecraft 1.13.2. Note that the redstone signal is extremely weak for the light pressure plate, as it is based on the *number of entities* on the plate. You won't get a signal on the heavy one, as that needs at least 10 entities.

Can you conform that it will not produce a measurable redstone signal with a wooden pressure plate? As that one instantly activates fully.
