### ISSUE TITLE
Sword blocking disabled breaks offhand item use when holding sword in main hand

### ISSUE THREAD

**Issue by sjoerdtim** [gvlfm78/BukkitOldCombatMechanics#325]
# Info

- Server version: git-Paper-639 (MC 1.13.2)
- OldCombatMechanics version: 1.7.3
- OldCombatMechanics config file: https://pastebin.com/2J0sb59C

## Problem Description
I have disabled sword blocking, since I don't want it.
However, every time I try to right click with something in my offhand (for example, shooting a bow or eating food), while holding a sword in my main hand, it keeps refreshing the offhand item so I can never finish drawing the arrow or eating.

I have tried multiple options, but it seems that even though I disabled sword blocking, the logic still does something to my offhands.

**Comment by I-Al-Istannen** [comment]
I can not reproduce this on 1.13.2 paper or 1.14.4 spigot with OCM 1.7.4-beta.

Do you have any other plugins installed? Can somebody else reproduce this issue? Does it also happen when you have just OCM installed?

**Comment by gvlfm78** [comment]
I am unable to reproduce this with OCM 1.7.4-BETA and 1.14.4 Paper. I turned off the sword-blocking module, and tried with both the disable-offhand module off and on with exceptions for BOW. I do not see this issue. @sjoerdtim Are you sure there isn't another plugin interfering?

**Comment by sjoerdtim** [comment]
It turns out this was a bug caused by a different plugin. My apologies for the false report.
