### ISSUE TITLE
Enderpearl spam won't disable

### ISSUE THREAD

**Issue by ManOfPaper891** [gvlfm78/BukkitOldCombatMechanics#326]
## Info

- Server version: This server is running Paper version git-Paper-137 (MC: 1.14.4)
- OldCombatMechanics version: 1.7.3
- Server log file: 
https://pastebin.com/eYmvNqv5
- OldCombatMechanics config file: 
https://pastebin.com/899geRaY

## Problem Description
> I can still spam enderpearls. The disabled cooldown, despite me still wanted it, is still enabled. I have tried both options and I can't seem to get a config that keeps the cooldown enabled.

**Comment by Rayzr522** [comment]
So just to clarify, you would like the 1.9+ cool down on enderpearls, but you can't seem to disable OldCombatMechanics' enderpearl module?

**Comment by ManOfPaper891** [comment]
> So just to clarify, you would like the 1.9+ cool down on enderpearls, but you can't seem to disable OldCombatMechanics' enderpearl module?

Correct. I want the cooldown.

**Comment by I-Al-Istannen** [comment]
@ManOfPaper891 

I could not reproduce this on 1.13.1.

On 1.14.4 I had no cooldown **even without having OCM installed.** So this does not quite look like an issue with this plugin. Can you try it without OCM and see if you have a cooldown?

**Comment by gvlfm78** [comment]
Indeed I confirm that with a completely newly setup 1.14 server with no plugins, even though I see the enderpearl cooldown animation, there is no effective cooldown. This appears to be a Bukkit bug, as I have just tested this with blank 1.14.4 Paper, Spigot, Bukkit and Vanilla servers and only in Vanilla there is enderpearl cooldown.
