### ISSUE TITLE
Old Tool Damage not applying to Wood and Gold Weapons/Tools

### ISSUE THREAD

**Issue by RarePika** [gvlfm78/BukkitOldCombatMechanics#329]
## Info

- Server version: CraftBukkit version git-Spigot-5e4e7f3-2349feb (1.14.3)
- OldCombatMechanics version: v1.7.3 (Also tested on v1.7.4-BETA)
- Server log file: https://pastebin.com/actf5eyd
- OldCombatMechanics config file: https://pastebin.com/HUm0fZ1P

## Problem Description
> Old Tool Damage not applying to Wood and Gold Weapons/Tools

When I installed OldCombatMechanics for my Spigot 1.14.3 server, I realized that the old-tool-damage module was having issues. After further research, I noticed that the custom item damages were being applied to every weapon/tool **except for the wooden and golden ones**.

To test this, I set every sword's damage to 100 in the config. This is what it looks like.
![1c](https://user-images.githubusercontent.com/17325905/62002650-9ff21880-b0c5-11e9-99cc-096c243109fa.png)

**And here is the resulting in-game item damages**

Wooden Sword:
![2019-07-27_23 12 52](https://user-images.githubusercontent.com/17325905/62002610-bf3c7600-b0c4-11e9-90ed-2f355f6a46a5.png)
Golden Sword:
![2019-07-27_23 12 58](https://user-images.githubusercontent.com/17325905/62002614-ca8fa180-b0c4-11e9-89f5-74b6b011f679.png)
Stone Sword:
![2019-07-27_23 13 13](https://user-images.githubusercontent.com/17325905/62002617-d4190980-b0c4-11e9-9c5c-9eedd997ad94.png)
Iron Sword:
![2019-07-27_23 13 28](https://user-images.githubusercontent.com/17325905/62002620-d8ddbd80-b0c4-11e9-97cd-91adf9436399.png)
Diamond Sword:
![2019-07-27_23 13 47](https://user-images.githubusercontent.com/17325905/62002623-e135f880-b0c4-11e9-83ed-ddc97a1561d0.png)

I tested this on axes also, and the same thing happened.

Please fix this as soon as possible. I have to leave the module disabled for now, making axes stupidly overpowered. I wouldn't want it to be that way for too much longer.

Thank You!
- RarePika

**Comment by gvlfm78** [comment]
This is happening because with 1.14 Bukkit changed the Material names of GOLD and WOOD weapons to GOLDEN and WOODEN to match vanilla Minecraft's naming scheme. We are currently working on fixing this.

**Comment by gvlfm78** [comment]
@RarePika Please try[ test build 59](https://ci.rayzr.dev/job/OldCombatMechanics/59/), the issue should now be fixed there.

**Comment by RarePika** [comment]
It's working properly now. Thank you!
