### ISSUE TITLE
NoClassDefFoundError EnchantmentType on player damage

### ISSUE THREAD

**Issue by Yokaos** [gvlfm78/BukkitOldCombatMechanics#333]
## Info

- Server version: Spigot 1.9.2 R0.1
- OldCombatMechanics version: 1.7.3
- Server log file: https://pastebin.com/raw/48JwMYNe
- OldCombatMechanics config file: https://pastebin.com/raw/bFbkCX9z

## Problem Description
> 
I get this error every time a player takes damages.

**Comment by gvlfm78** [comment]
I believe this may be the same issue as #313, which has been fixed in the beta builds. Please try a [test build](https://ci.rayzr.dev/job/OldCombatMechanics/) from the Jenkins server and see if the issue is still there.
