### ISSUE TITLE
Cant disable the plugin/attack speed is stuck 

### ISSUE THREAD

**Issue by JMGamingandStuff** [gvlfm78/BukkitOldCombatMechanics#334]
## Info

- Server version: 
- OldCombatMechanics version: 
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> Hello,
I wanted to try out this plugin on my server but I did not like it and uninstalled it by removing both the jar file and the configuration folder. The attack speed is still stuck and I can still spam click. Any suggestions on how to fix it?
Thanks,
Jack

**Comment by JMGamingandStuff** [comment]
Sorry I forgot about labels.

**Comment by JMGamingandStuff** [comment]
Srry again forgot about the info 

Info:
Server version: 1.14.4
OldCombatMechanics version: 1.7.3
Server log file: 
[latest.log](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/3490476/latest.log)
OldCombatMechanics config file:
[config.txt](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/3490478/config.txt)

Really sorry for semi spam

**Comment by JMGamingandStuff** [comment]
fixed

**Comment by gvlfm78** [comment]
@JMGamingandStuff May I know how you tried to uninstall OCM, and how you fixed it?

There are a lot of users complaining that the attack speed gets stuck but no one is ever able to explain what they did to 'uninstall' the plugin that caused the issue.
