### ISSUE TITLE
Suggestion : Add BungeeCord

### ISSUE THREAD

**Issue by EarthAgar** [gvlfm78/BukkitOldCombatMechanics#335]
Suggestion : Add BungeeCord

**Comment by detobel36** [comment]
To do what ?

It's fully compatible with BungeeCord no ?

**Comment by EarthAgar** [comment]
No, I'm making a suggestion to make it Bungee Compatible

**Comment by Rayzr522** [comment]
In what way is it not compatible already?

**Comment by EarthAgar** [comment]
*extreme facepalm* Im bew to using bungee cord and so from what i know i
need an option for bungee in a plugin to make it work across all servers.

**Comment by Rayzr522** [comment]
Nope, you just install it into the plugins folder of each server (but not of bungee!). The only possible feature that could be added related to bungee cord would be some kind of settings-sync between the individual servers, but I don't think that is really very beneficial for OCM. I am closing this for now.
