### ISSUE TITLE
Removing plugin deleted playerdata

### ISSUE THREAD

**Issue by NEvana0003** [gvlfm78/BukkitOldCombatMechanics#336]
## Info

- Server version: 1.14.3
- OldCombatMechanics version: not sure, got it 2 days ago
- Server log file: https://pastebin.com/aSKWXgeK
- OldCombatMechanics config file: was deleted

## Problem Description
> I had an issue with the combat being stuck, and after following instructions to fix said problem, my player data for everyone was deleted. luckily i had a backup made, but this is still an inconvenience. 

It seems this plugin uses nbt data to function, and i was wondering if you had the path so i can fix it myself manually, OR if you know an easier way.

**Comment by NEvana0003** [comment]
sorry, i was unclear. i was wondering if you had the path of the nbt that the plugin changes, so i can unstick(?) my combat

**Comment by Rayzr522** [comment]
Hmm, did you use Plugman or `/reload` to uninstall the plugin, or did you properly shut down the server before removing the plugin? 

But either way, you can use [OCMFixer](https://github.com/Rayzr522/OCMFixer.git) to fix the playerdata for your players.

**Comment by NEvana0003** [comment]
I did use /reload, and i will try OCMFixer. i assumed it would also delete the playerdata, but will give it a shot.

**Comment by NEvana0003** [comment]
Awesome. worked perfectly, thank you for the quick response.
