### ISSUE TITLE
Auto Shield Deploy & Off-Hand

### ISSUE THREAD

**Issue by Crispyyyyy** [gvlfm78/BukkitOldCombatMechanics#337]
I love this plug-in and I use it on my server but I hate how whenever I right click with a sword out that it auto deploys a shield, I also hate how I can't use my off-hand anymore. How do I change this?

**Comment by detobel36** [comment]
Did you take the time to read the configuration ?
https://github.com/gvlfm78/BukkitOldCombatMechanics/blob/master/src/main/resources/config.yml

Like:
```
disable-offhand:
  # Disable the usage of the offhand
  # Won't affect sword-blocking module
  enabled: true
```
Or:
```
sword-blocking:
  # This is to allow players to block with swords again, by getting a shield while they hold right click with a sword
  enabled: true
```

**Comment by Rayzr522** [comment]
Thank you @detobel36, that is correct. You can easily disable these through the config. It is full of comments, it should be relatively straightforward to disable these features.

**Comment by Crispyyyyy** [comment]
I can turn off the shield auto deploy but I still can't use my offhand for some reason.
