### ISSUE TITLE
Sweeping Edge

### ISSUE THREAD

**Issue by MineStroke** [gvlfm78/BukkitOldCombatMechanics#338]
Whenever I enable sweeping edge, every kind of sword has sweeping edge no matter if the enchantment "Sweeping Edge" is on it or not, even if the sword has NO enchantments, it still has the Sweeping Edge affect

**Comment by gvlfm78** [comment]
Do you mean the _Sword Sweep_ attack? All swords have that, the _Sweeping Edge_ enchantment just makes it deal more damage.

**Comment by MineStroke** [comment]
So there is no way to have it where only swords enchanted with Sweeping Edge will have the sword sweep attack?

**Comment by gvlfm78** [comment]
There's probably a way to have that, but I don't believe it's the concern of this plugin to implement such a feature.
