### ISSUE TITLE
Fix the bow damage.

### ISSUE THREAD

**Issue by ItzVinex** [gvlfm78/BukkitOldCombatMechanics#34]
Fix the bow damage.

Most plugins don't handle this. You should make the bow damage back to 1.8 modifiers.

**Comment by gvlfm78** [comment]
I believe this is already in the to do list, although I couldn't find much information on how the exact values changed

**Comment by ItzVinex** [comment]
Yeah legit I tiredness doing myself I managed but I couldn't be exactly make the the damage range I did an exact set amount. Also if you browse the  you'll able to see how 1.9 changes the bow it doesn't 9 damage compared to the old one it's like 2 - 4

**Comment by gvlfm78** [comment]
Hmm actually I don't see any mention of the bow damage changing in the 1.9 patchnotes, where did you find that it had changed?

**Comment by ItzVinex** [comment]
Go in a 1.9 server and above and hit a someone with an arrow from a bow it doesn't like 9 sometimes 4 hearts and check the wiki it show it does 9 hearts.

**Comment by gvlfm78** [comment]
But you tested this without them having armour on and at full bow extension?

**Comment by ItzVinex** [comment]
Full Iron armor and bow full charged and half charged around 4 hearts.

**Comment by gvlfm78** [comment]
You need to try it without armour because the armour strength changed from 1.8 to 1.9

**Comment by ItzVinex** [comment]
You should add in the armor then that'd be great.

**Comment by gvlfm78** [comment]
It already is in the plugin
