### ISSUE TITLE
mcmmo and off hand

### ISSUE THREAD

**Issue by TwerkRekt** [gvlfm78/BukkitOldCombatMechanics#340]
## Info

- Server version: 1.12.2
- OldCombatMechanics version: 1.7.4
- Server log file: none
- OldCombatMechanics config file: none

## Problem Description
> 
With latest version of oldcombatmechanics MCMMO spam with off hand on right-click

**Comment by gvlfm78** [comment]
Can I have more detail as to what this means? What is it that you can spam?
