### ISSUE TITLE
Offhand is not Working

### ISSUE THREAD

**Issue by Grantawe** [gvlfm78/BukkitOldCombatMechanics#345]
Server Version: 1.14.4
OCM Version: 1.7.4
Config for Offhand: https://pastebin.com/BdTvBLNX

Offhand is not working.
Whenever I try to use F (the key to switch an item into the offhand) nothing happens.
When I try to manually put an item in via the inventory it just sends it back out.

**Comment by I-Al-Istannen** [comment]
Are you sure it is OCM interfering? Do you have any other plugins?

**Comment by Grantawe** [comment]
I have lots of other plugins, here is the list.

SpawnerSilk 
Grief Prevention  
Disable Elytra    
Multiverse-NetherPortals    
Multiverse-Portals    
Multiverse-Core    
OldCombatMechanics   
AcceptRules
WorldEdit
Timber Plugin
AltAccountAutoban
EnchantPlus
WorldGuard
DropHeads
Multiverse-Inventories
OpenInv
LaggRemover
etwChat    
Chairs Reloaded
CoreProtect
AFK
DeepVanish
Sleepy
JoinMessagePlus
ChatClear [cc]

Im not 100% sure if its OCM but it's the only thing that changes stuff like this so I immediately thought it would be.

**Comment by Rayzr522** [comment]
Please try the following:
1. Stop the server.
2. Remove the OldCombatMechanics JAR from your plugins folder.
3. Start the server again.
4. Check to see if the issue is still present without OldCombatMechanics installed.

If that solves the issue, then something is wrong with your OCM config file. A full server log with OldCombatMechanics installed would be quite helpful.

**Comment by Grantawe** [comment]
It works now, how can I get a server log?

**Comment by Rayzr522** [comment]
Firstly, stop the server & reinstall OldCombatMechanics. Then, after you run the server again and it has finished starting up, look in the `logs` folder for a file called `latest.log`. That is the server's log file.

**Comment by Grantawe** [comment]
Here is the OCM startup from latest.log
https://pastebin.com/eHZ21rir

**Comment by I-Al-Istannen** [comment]
Your OCM config is invalid. We should probably just refuse to load anything in that case.

Please post your whole config.

**Comment by Grantawe** [comment]
Here is the full config, apologies for not posting it in it's entirety earlier.

https://pastebin.com/y24CVPhp

**Comment by I-Al-Istannen** [comment]
Please close the `interative` list with a closing square bracket:
```yaml
interactive: [enchantment_table,anvil,brewing_stand,trapped_chest,chest,bed,boat,fence_gate,dispenser,dropper,furnace,jukebox,ender_chest,stone_button,wood_button,beacon,tripwire_hook,hopper,daylight_detector,daylight_detector_inverted,item_frame,diode,diode_block_off,diode_block_on,redstone_comparator,redstone_comparator_off,redstone_comparator_on,acacia_door,birch_door,dark_oak_door,jungle_door,spruce_door,wood_door,workbench,bed_block,lever,trap_door,burning_furnace,spruce_fence_gate,birch_fence_gate,jungle_fence_gate,dark_oak_fence_gate,acacia_fence_gate,white_shulker_box,orange_shulker_box,magenta_shulker_box,light_blue_shulker_box,yellow_shulker_box,lime_shulker_box,pink_shulker_box,gray_shulker_box,silver_shulker_box,cyan_shulker_box,purple_shulker_box,blue_shulker_box,brown_shulker_box,green_shulker_box,red_shulker_box,black_shulker_box]
```
Then try again and check for any errors in the console. you can also check your config file [here](http://www.yamllint.com/) (or on similar sites).

If it still doesn't work, report back please.

**Comment by Grantawe** [comment]
I added the bracket to the end of the interactive line, still doesn't work.

I also think nocooldown is broken as well, the indicator doesn't show up but everything fells like it does no damage when spamclicking.

**Comment by I-Al-Istannen** [comment]
Can you try *just OCM on a test server with the same version* and see if the problem persists? If not, another plugin is causing an incompatibility. If it still persists, the startup log of the server up until OCM was loaded (and maybe a bit more) would be interesting.

**Comment by Grantawe** [comment]
I turned off every plugin besides OCM and offhand does not work.
What can we do?

**Comment by Rayzr522** [comment]
Please back up your OCM config.yml file, delete it, let it re-generate the default one, and from there turn off the `disable-offhand` module. I still suspect it's something wrong with your config, although I did not see anything when I skimmed briefly over your config.

**Comment by Grantawe** [comment]
I reset the config and added all the same values I had before,
it works now! Thank you so much for your help!

**Comment by Rayzr522** [comment]
Interesting, there must have been something wrong with your config. Glad it's working now!
