### ISSUE TITLE
Offhand module blocking access to all slot #40s

### ISSUE THREAD

**Issue by matt-malle** [gvlfm78/BukkitOldCombatMechanics#36]
For some... odd reason.. I can't place items in the #41 slot in a chest. 

I know that sounds like nonsense, but I've tried doing it without combat mechanics installed and it works fine. I tried downloading the latest dev version and that didn't fix it either. 

Here's my config: https://hastebin.com/idozaqetuk.bash
The only error I'm getting: https://hastebin.com/gikawukuge.pl
Server version: Paper version git-Paper-916.2 (MC: 1.10.2) Implemetning API version 1.10.2-R0.1-SNAPSHOT)
Gif: https://gyazo.com/ebc68023b608cd886c1240a2120896ad

**Comment by gvlfm78** [comment]
Could you try disabling the disable-offhand module and see if the issue is still present?

**Comment by matt-malle** [comment]
Disabling it does fix it, but I would rather not allow offhand. :/

**Comment by gvlfm78** [comment]
Ok I will look into the module to attempt fixing the bug.

**Comment by gvlfm78** [comment]
@matt-malle Could you try test build [#49](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/) from the Jenkins server?

**Comment by matt-malle** [comment]
That fixed it :) Sorry for the late reply!
