### ISSUE TITLE
Two offhand problems

### ISSUE THREAD

**Issue by 0x1x2** [gvlfm78/BukkitOldCombatMechanics#37]
Hi!

Two bugs with the off-hand in the plugin.

First, with a whitelist, I still cannot use the F (or key for equipping offhand) to equip the item even if the item is in the offhand.

Second, if I put an item in my offhand that is permitted with a whitelist, I can then put in one that isn't and it would stay there. 

Server on 1.10.2, OCM version 1.1.2.

**Comment by gvlfm78** [comment]
OK, can you try the latest development version at https://jenkins-gvl.rhcloud.com/ about the first bug? I seem to remember fixing something very similar. 

About the second one, someone else signalled it but I couldn't understand what they were saying so I was unable to replicate it. I will try again and let you know when I've fixed it.

**Comment by gvlfm78** [comment]
Ok I fixed the second bug in build #54. @0x1x2 Could you check if the bugs have been fixed for you too?
