### ISSUE TITLE
PlayerJoinEvent Lag

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#4]
Any way to optimize PlayerJoinEvent lag caused by OCM? What requires listening for the join event? The 'Better Combat' plugin isn't even a fraction of the performance cost. :s 

![link](http://i.imgur.com/AOqnUMl.png)

**Comment by mibby** [comment]
Seems to be causing lag spikes any time someone connects / relogs.
![link2](http://i.imgur.com/NxxKAGb.png)

**Comment by gvlfm78** [comment]
Yes there is a way to optimise it, I was already planning on working on it today. It's the update checker that runs when an op logs in, and I'm going to move it into an asynch task so that it doesn't lag the player on login. At least I believe that is the problem.

**Comment by gvlfm78** [comment]
Ok I have made both the onPlayerJoin and the onEnable update checks run asynchronously as well as fixing a small problem that was preventing the Bukkit update checker from working.

**Comment by mibby** [comment]
That's odd. I had the update check disabled and no one is op, nor was any admin with a wildcard permission flag relogging. 

In any case, thanks. I'd like OCM to be as lightweight as possible. :)

**Comment by gvlfm78** [comment]
Well I moved the permission check from inside the update checker to the listener so that it doesn't run anything if the player doesn't have the permission.
