### ISSUE TITLE
Utility to scan and reset all player attributes to vanilla default.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#40]
@gvlfm78 Is it at all possible to create a small utility to scan the world folder and reset all player.dat file attributes to their vanilla default values? Somehow I have some players with a generic.attackDamage of base 7, while most others have generic.attackDamage of 1. This is causing those players to be extremely powerful in arenas. I have no idea how their attribute got set so high but I also am not familiar with how to reset everyone without wiping everyone's location / inventory, since I do not know who else is broken.

It may be related to these issues that were marked fixed, but those players were never fixed directly.
https://hub.spigotmc.org/jira/browse/SPIGOT-2077
https://hub.spigotmc.org/jira/browse/SPIGOT-704
https://hub.spigotmc.org/jira/browse/SPIGOT-1409

**Comment by Rayzr522** [comment]
(OCMFixer)[https://github.com/Rayzr522/OCMFixer) should do the trick

**Comment by gvlfm78** [comment]
But why do some players have a different attack damage? Our plugin doesn't modify that one the player, but on the weapons separately

**Comment by mibby** [comment]
No idea. Just something that was reported to me so I looked into the user's nbt attributes to see he has higher damage. Not sure how many are affected.

**Comment by Rayzr522** [comment]
As @gvlfm78 said, our plugin doesn't modify the user attack _damage_, but I'm sure I could expand OCMFixer to fix attack damage too. I should have it done some time tomorrow.

**Comment by Rayzr522** [comment]
@mibby [OCMFixer v1.1.0 is out now](https://github.com/Rayzr522/OCMFixer/releases).
