### ISSUE TITLE
Shields turning into books

### ISSUE THREAD

**Issue by Mikgreg** [gvlfm78/BukkitOldCombatMechanics#43]
Hello!

Having a bit of a weird issue here. We use OldCombatMechanics to bring up a shield whenever people right click with their sword, but if they crouch and left click their shield will turn into a book and quill for some reason.

We have not been able to observe this behavior on a server without OldCombatMechanics on it.

Plugin version: 1.1.2
Spigot version: Paper 1062

**Comment by gvlfm78** [comment]
Our plugin contains no code that would do such a thing. It is something very specific, changing an item while also shifting while also blocking.

You having not been able to observe this on a server without OCM is inconclusive evidence that it is OCM, as if it is a conflict between plugins removing either would make it work.

For now I can suggest trying out the [newest development build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/), but without further information and being able to replicate the bug I cannot proceed.
