### ISSUE TITLE
Lore text displaying wrong damage values

### ISSUE THREAD

**Issue by lelodragneel** [gvlfm78/BukkitOldCombatMechanics#45]
Weapons and tools such as Swords, axes, shovels, etc are displaying the wrong damage values. For instance, the Iron Axe says it deals 9 Attack Damage, but the hits are dealing 5 damage.
[Value](https://i.gyazo.com/92999ea1eb2ed742a21de3b03c4d6c9e.png)
[Damage](https://i.gyazo.com/375f1cc8e45bf03eeef008c075514c97.png)

This bug has been tested on a fresh server with only the following mods installed:
CombatIndicator_2.0.14.jar
HolographicDisplays.jar
OldCombatMechanics.jar

Here's the config:
http://pastebin.com/M2kDGw6W

Finally, the server is running  git-Spigot-283de8b-2ad21b8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by gvlfm78** [comment]
Thank you for reporting in such detail, but this is not a bug, rather how the plugin works. For efficiency purposes the plugin intercepts the damage and changes the value when the damage is done, instead of modifying the NBT values of each individual item.

**Comment by gvlfm78** [comment]
Thank you for reporting in such detail, but this is not a bug, rather how the plugin works. For efficiency purposes the plugin intercepts the damage and changes the value when the damage is done, instead of modifying the NBT values of each individual item.

**Comment by lelodragneel** [comment]
Ahh I see. Thank you for the fast response. Great plugin by the way, I love it.
Is there a complimentary plugin you would suggest that allows for modifying NBT values?
