### ISSUE TITLE
Custom tool damage issues

### ISSUE THREAD

**Issue by AlexBaber** [gvlfm78/BukkitOldCombatMechanics#46]
Having some issues with this plugin, first off all configuring the tool damage is quite confusing, and sometime when I reload the plugin it breaks the config. Is there a way you can make it so the attack damages are on the tools too? Also, I have other hand disabled but people can still use their other hand. Please help.

**Comment by gvlfm78** [comment]
It is explained in the config in the relevant section what the tool damage does, and the fast that this is not reflected in-game as it would be terribly inefficient to do so.

About the offhand module, what are your settings for that section?
What version of the plugin do you have?
In what way can people still use the offhand?

**Comment by Rayzr522** [comment]
The tool damage is actually quite easy to configure: You know the damage on the tooltip? The numbers in the config are used to _divide_ the base damage. We've used this to simulate the old damages, but you can use it to make the damage anything you like. For example, if you set the `DIAMOND_AXE` number to `2`, it would do half the damage that's listed on the tooltip. If you set it to `0.5`, it would double it.

It's not only extremely inconvenient to modify the actual NBT of the items (which is what we originally were going to try), but it's much less efficient and _waaaaay_ more likely to cause problems.

As to the offhand problem, we just need to know a little more about your situation, as @gvlfm78 said.

**Comment by AlexBaber** [comment]
Okie, doke, just sometime when I try change the axe damage it doesn't actually change in game (not just the tooltip) - I have the disable-off hand as enabled, the player collision is also enabled but doesn't work for me..

**Comment by AlexBaber** [comment]
Hello, still having issues with the tool damage. For example I put the axe on 2, it does 4 hearts (sharp 5 + unarmed) but then I change it to a higher number and nothing changes.

**Comment by gvlfm78** [comment]
Are you reloading the plugin after every change? 

Also, can you enable debug messages in the config? (IIRC there's messages whenever damage is applied. If not, I'll add them)

**Comment by AlexBaber** [comment]
I was reloading it, just tried it without reloading the plugin, off hand is still not working for me. THINK I sussed out the axe damage. Also, you can still push people with it being toggled. [Here's](http://imgur.com/a/TZSDl) a debug message of the axe and also a pastern of my config. http://pastebin.com/BdMjNdy7

**Comment by gvlfm78** [comment]
There have been many bug fixes to the plugin lately. Please update OCM and if you find any issues open a new ticket for each new issue.
