### ISSUE TITLE
Disable-OffHand number keys

### ISSUE THREAD

**Issue by xDominiKK** [gvlfm78/BukkitOldCombatMechanics#48]
I found a bug with 'disable-offhand'
When we put a locked item on the hotbar and hover the mouse over the slot from this hand, we can put it there.

My Configuration:
`disable-offhand:
  enabled: true
  worlds: []
  whitelist: false
  items: [diamond_sword]`

**Comment by gvlfm78** [comment]
Test build [#66](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/66/) should fix this issue

**Comment by xDominiKK** [comment]
Now you can not move any items, and when the slot is inserted an unopened item, we can move the locked item.
Sorry for my English.

[https://gyazo.com/ab0c1451363432792962284043b7686e](url)
[https://gyazo.com/46cd5e647b1a1010407a326dccf4a8ea](url)

**Comment by gvlfm78** [comment]
I'm not sure what you mean, but I fixed the reloading of the list in build [#67](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/67/)

**Comment by xDominiKK** [comment]
I do not know how to describe it so I recorded it.
I hope you understand what's going on.

[https://www.youtube.com/watch?v=Eisgj6sSu8M&feature=youtu.be](url)

My configuration:

`disable-offhand:
  # Disable the usage of the offhand
  # Won't affect sword-blocking module
  enabled: true
  worlds: []
  # Whether the following list blocks items or allows them
  whitelist: false
  # List of items that should be allowed/not
  # Example: [diamond_sword,BOW]
  items: [diamond_sword]`

**Comment by gvlfm78** [comment]
I see now. Can you check if the problem still occurs in build [#69](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/69/)? I went for the nuclear option and just stopped being able to move items with number keys into the offhand slot while the module is enabled.

**Comment by xDominiKK** [comment]
Okay, but it is not possible now to throw things to the offhand. 👍 
[https://www.youtube.com/watch?v=lO9RquNwkVk&feature=youtu.be](url)

**Comment by gvlfm78** [comment]
When you try to move items into the offhand slot, the event the plugin is listening for tells the plugin that you are holding air, there is air in the slot you're putting the item in, and the whole inventory is null. Go figure. That means I can't check what item is getting transferred so I just blocked all items.
