### ISSUE TITLE
Option to enable snowball knockback on player hit.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#49]
Apparently snowball/egg knockback was a longstanding bug in Spigot and wasn't suppose to be a thing. 
https://www.spigotmc.org/threads/bug-or-feature-snowball-egg-knockback.214759/#post-2232519

Would it be possible to implement an OCM module to allow for snowball/egg player knockback and/or damage? As it was a prevalent thing in my PVP arena community. :(

**Comment by gvlfm78** [comment]
Can you test out the projectile knockback module in [build #70](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/70/)? I'm not entirely sure I got the knockback values correct

**Comment by mibby** [comment]
@gvlfm78 It seems you are able to hurt and knockback players who have godmode on in survival, who are in creative, and who are in non-pvp areas. Would it be possible to only allow for knockback / damage if players are able to get hit / pvp normally?

**Comment by mibby** [comment]
As for the knockback values itself, I'm not entirely sure what the default would be. Instead of artificially moving players a distance and doing damage, would it be better to just do a standard hit damage event that normally applies a knockback effect?

Something similar to this plugin.
https://www.spigotmc.org/resources/snowball-damage.16740/

**Comment by gvlfm78** [comment]
I just released an update for this, as it is a serious issue to be able to damage players while in creative mode/protected areas. I also made it so it doesn't add knockback artificially, but simply alters the damage when hit by a snowball/egg/enderpearl
