### ISSUE TITLE
Golden Apple bug

### ISSUE THREAD

**Issue by nekosquishy** [gvlfm78/BukkitOldCombatMechanics#5]
There seems to be a infinite gapple bug, whenever i eat an apple it doesnt dissapear and i can keep eating the same apple

**Comment by Rayzr522** [comment]
What version of server are you using, and are you getting any errors?

**Comment by nekosquishy** [comment]
1.10 and im not sure how to check for error

**Comment by Rayzr522** [comment]
Do you have acces to the console?

**Comment by nekosquishy** [comment]
yes

**Comment by gvlfm78** [comment]
Are there any errors in the console when this happens? Also, what version of the plugin are you using?

**Comment by gvlfm78** [comment]
Is it a normal golden apple or an enchanted one? What are your settings in the config.yml under the old-golden-apples section? How many apples are you holding while testing this?

Sorry for the spam of questions, but I do not seem able to replicate the bug

**Comment by nekosquishy** [comment]
ok ill get all that information for u now 1 second

**Comment by nekosquishy** [comment]
im using version 0.9

**Comment by nekosquishy** [comment]
i also have essentials installed, would that mess with anyhting

**Comment by nekosquishy** [comment]
http://pastebin.com/pvU3jf47

**Comment by nekosquishy** [comment]
heres a paste bin of the console, i cant see any errors

**Comment by gvlfm78** [comment]
No, I do not see any errors.

**Comment by gvlfm78** [comment]
Where did you download this version from?

**Comment by nekosquishy** [comment]
:L i had a thought that it might me just be essentials but i removed your plugin and apples behave normally, would it help if i made a video on exactly what happens

**Comment by gvlfm78** [comment]
Don't worry, we managed to replicate the bug - now we need to try to fix it

**Comment by nekosquishy** [comment]
ahh ok sweet

**Comment by Rayzr522** [comment]
Try this build:
https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/28/

**Comment by Rayzr522** [comment]
Actually here:
https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/29/
There was a slight problem with it

**Comment by gvlfm78** [comment]
@nekosquishy Can you tell us if it works with that release? We need to know as we are planning on releasing an update now.
