### ISSUE TITLE
Add a nametag at the bottom of tools that says 1.8 Damage Values.

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#50]
Some servers that are 1.11 have a thing at the bottom of every tool that says 1.8 Damage Values. To let players know i was wondering if this is possible to add to the plugin.

**Comment by Fonzee9** [comment]
Here is an example of the nametag for 1.8 damage values: http://imgur.com/CZoeTgT

**Comment by Rayzr522** [comment]
There's no real good way to do this short of modifying outgoing packets. We don't want to modify the data of the items themselves, as then it's virtually impossible to reset if the module is disabled later on. It's possible, but again, it would require modifying outgoing packets. @gvlfm78 it's up to you.
