### ISSUE TITLE
Per world system is broken

### ISSUE THREAD

**Issue by TheWranger** [gvlfm78/BukkitOldCombatMechanics#51]
I have a world named 1.8 so I changed the config option for all the plugin features from
worlds: []
to
worlds: [1.8]
and now the plugin won't work in any worlds at all.

Tried using PerWorldPlugins as well but it seems it doesn't limit the combat change to certain worlds...

**Comment by detobel36** [comment]
No... You must to make this:
```
worlds:
- 1.8
```

**Comment by Rayzr522** [comment]
@detobel36 that's the same thing. YAML array syntax is valid either way.

**Comment by TheWranger** [comment]
Could it be because it's a world with a numbered name?

**Comment by gvlfm78** [comment]
I did think of that but I didn't get time to check if that changed anything.

**Comment by TheWranger** [comment]
Just tested this on my dev server and the numbered name seems to be the cause.

**Comment by gvlfm78** [comment]
@TheWranger Could you try [test build #68](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/68/) and see if the issue is still present?
