### ISSUE TITLE
Cannot Restore Cooldowns

### ISSUE THREAD

**Issue by Eko1823** [gvlfm78/BukkitOldCombatMechanics#52]
My players decided they wanted the new combat mechanics so that right-clicking wouldn't interfere with McMMO.
After removing the .jar and the plugin folder, the cooldown animation has not restored to their screens (nor mine). I'm wondering what I did wrong?

**Comment by Rayzr522** [comment]
You stopped the server and then removed the JAR file?

**Comment by Eko1823** [comment]
Yes, I did.
I stopped the server, took out the .jar and the folder, and started it back up again.

When I added the .jar back to see if I could change anything, the plugin seemed to stop working (however, the command /plugins shows OldCombatMechanics as working).
Although there is no cooldown animation, the sweeping attack that damages all mobs in an area now works with OldCombatMechanics is installed. In addition, no shield pops up when users right-click.

**Comment by gvlfm78** [comment]
What version of the plugin are you using now?

**Comment by Eko1823** [comment]
The latest release, version 1.4.0.

**Comment by gvlfm78** [comment]
Have you tried at least reloading if not restarting your server?

**Comment by Eko1823** [comment]
Yes, I have.

**Comment by gvlfm78** [comment]
It is very strange that the plugin no longer functions on your server, but if for some reason you find that the cooldown was not removed, you can have a look at issue #11 and:

1. Remove OCM entirely
2. Install the [OCMFixer](https://github.com/Rayzr522/OCMFixer) plugin
3. Run the OCMFixer plugin as documented [here](https://github.com/Rayzr522/OCMFixer)
4. Remove the OCMFixer plugin, and check if the cooldown was removed or not.

**Comment by Eko1823** [comment]
This fixed the issue. Thank you so much. :)
