### ISSUE TITLE
Config always resetting

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#56]
Ever since i updated oldcombatmechanics my config keeps resetting no matter what.

**Comment by gvlfm78** [comment]
Plugin and config versions?

**Comment by Fonzee9** [comment]
config-version: 10

I was on the Latest version but had to downgrade to stop config from reseting.

**Comment by Fonzee9** [comment]
Whole config that resets when updating to latest version: https://pastebin.com/usVN8Udf

**Comment by gvlfm78** [comment]
What version of the plugin are you using?

**Comment by Fonzee9** [comment]
I was using the latest but it kept reseting the config whenever i would change it so i went back to build 68 until the problem is fixed.

**Comment by gvlfm78** [comment]
Does build [#75](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/75/) have this issue?

**Comment by Fonzee9** [comment]
Yup already tested it samething resets the config.

**Comment by gvlfm78** [comment]
What is the message displayed in the console when the reset occurs?

**Comment by Fonzee9** [comment]
[16:32:35 INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v1.3.1
[16:32:35 WARN]: [OldCombatMechanics] Config version does not match, backing up old config and creating a new one
[16:32:35 INFO]: [OldCombatMechanics] OldCombatMechanics v1.3.1 has been enabled correctly

**Comment by Fonzee9** [comment]
Even though it says that i already redid the new config with my changes and it still reset.

**Comment by Fonzee9** [comment]
When will this be fixed?

**Comment by gvlfm78** [comment]
I haven't been able to replicate this issue so I cannot solve it until I know where the problem is. I need more information, such as what config version the plugin is resetting you from and to, the server version, and the plugin version. Also make sure the plugin is upto date because the code changes every time.

**Comment by Fonzee9** [comment]
I found out the problem its:

**Comment by gvlfm78** [comment]
That is very strange. What update checker was it using, bukkit or spigot?
