### ISSUE TITLE
ERROR Could not pass event PlayerQuitEvent to OldCombatMechanics v1.3.1

### ISSUE THREAD

**Issue by CCCCarsten** [gvlfm78/BukkitOldCombatMechanics#57]
https://pastebin.com/H7Bbid03

Ciao, Carsten

**Comment by Rayzr522** [comment]
The armor that you were wearing, was it given via a command or plugin?

**Comment by CCCCarsten** [comment]
Hi Rayzr522,

the armor was given by commands... for example: /replaceitem entity CCCCarsten slot.armor.chest diamond_chestplate 1 3 {display:{Name:"Panzer"},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:20,Operation:0,UUIDMost:48737,UUIDLeast:90449}],ench:[{id:0,lvl:5},{id:1,lvl:5},{id:2,lvl:5},{id:3,lvl:5},{id:4,lvl:5},{id:5,lvl:5},{id:6,lvl:5},{id:7,lvl:5},{id:8,lvl:5},{id:16,lvl:5},{id:17,lvl:5},{id:18,lvl:5},{id:19,lvl:5},{id:20,lvl:5},{id:21,lvl:5},{id:32,lvl:5},{id:34,lvl:5},{id:35,lvl:5},{id:48,lvl:5},{id:49,lvl:5},{id:50,lvl:5},{id:51,lvl:5},{id:61,lvl:5}],HideFlags:7,Unbreakable:1}

Ciao, Carsten

**Comment by Rayzr522** [comment]
The problem is the command. The UUIDMost and UUIDLeast are not the correct type of value. They should be Longs, but I'm not sure how to represent that in a command. Maybe you can add `L` to the end of the numbers?

**Comment by CCCCarsten** [comment]
? Like this ? -->
/replaceitem entity CCCCarsten slot.armor.chest diamond_chestplate 1 3 {display:{Name:"Panzer"},AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:20,Operation:0,UUIDMost:48737L,UUIDLeast:90449L}],ench:[{id:0,lvl:5},{id:1,lvl:5},{id:2,lvl:5},{id:3,lvl:5},{id:4,lvl:5},{id:5,lvl:5},{id:6,lvl:5},{id:7,lvl:5},{id:8,lvl:5},{id:16,lvl:5},{id:17,lvl:5},{id:18,lvl:5},{id:19,lvl:5},{id:20,lvl:5},{id:21,lvl:5},{id:32,lvl:5},{id:34,lvl:5},{id:35,lvl:5},{id:48,lvl:5},{id:49,lvl:5},{id:50,lvl:5},{id:51,lvl:5},{id:61,lvl:5}],HideFlags:7,Unbreakable:1}

**Comment by gvlfm78** [comment]
I just tried it. That command does seem to work.

**Comment by Rayzr522** [comment]
Yes, just make sure to append `L` to the numbers in your UUIDLeast and UUIDMost.

**Comment by CCCCarsten** [comment]
Hi!

Ist seems that there are no errors after changing the commands... very good! :)
Thanks and

Ciao, Carsten
