### ISSUE TITLE
StackOverflowError generating new config.

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#6]
http://paste.ubuntu.com/18763869/

OldCombatMechanics dev 49
Generated a new config at server start-up, this overflow error occurred. It occurs every time the server starts.

Caused by this version not being updated?
https://github.com/gvlfm78/BukkitOldCombatMechanics/blob/b6484c31ba3827a0ef3da0c0628e85f97b335da6/src/main/java/gvlfm78/plugin/OldCombatMechanics/utilities/Config.java#L16

**Comment by Rayzr522** [comment]
Nice catch. Apparently when @gvlfm78 updated the config.yml version he forgot to change CONFIG_VERSION like you mentioned.

Try this: https://jenkins-bukkitocm.rhcloud.com/job/OldCombatMechanics/50/

**Comment by gvlfm78** [comment]
I knew I was going to mess something up by not testing it again...
