### ISSUE TITLE
Fishing rods bypass non-pvp regions

### ISSUE THREAD

**Issue by hasanas83V2001** [gvlfm78/BukkitOldCombatMechanics#60]
So, the fishing rods are finally working as they should (thank you) but now, they also work in non-pvp regions,eg: they can hit players at spawn, in towns, etc. This is a pretty big issue.

Kind regards,
hasanas

**Comment by gvlfm78** [comment]
Have you tried enabling the checkCancelled: option in the config under this module's section?

Also, ghacproductions just helped with the plugin and added an option for the plugin to call a different event, for compatibility purposes. This could possibly help, although I don't know your exact situation. If you wish to try out this new feature use test build [#105](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/105/) and up. (Your config will be backed-up and reset when updating to this version)

**Comment by ghacproductions** [comment]
With build [#106](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/106/) and up, you don't have to use the special event, but can just activate the checkCancelled option, the damage then gets tracked to the correct user (working for NCP & AAC).
