### ISSUE TITLE
Weapons go down when attacking

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#61]
When i hit a mob the weapon goes down like the new combat its really annoying.

**Comment by Fonzee9** [comment]
This doesn't happen with hit with my fist only with weapons

**Comment by gvlfm78** [comment]
What attack-speed value do the weapons display?

**Comment by Fonzee9** [comment]
21.6 also it only happens when your attacking mobs and players for example you can use a wood shovel and hit a zombie with it and pay attention to how the shovel goes down a lot instead of staying up like 1.8 would.

**Comment by gvlfm78** [comment]
I loaded into a 1.8 world and I now see what you mean, but unfortunately that is the way it works in 1.9+ and even increasing the attack speed doesn't remove the weapon going down animation.

**Comment by Fonzee9** [comment]
Theres no way you can tweak it to be a little less noticeable?

**Comment by gvlfm78** [comment]
No, I even tried setting the speed to 9999 and it makes no difference, unfortunately.

**Comment by Fonzee9** [comment]
The weirdest part is Mineplex upped there attack speed to 1023 and they don't have that annoying effect how did they fix it?

**Comment by Fonzee9** [comment]
I do it just annoys me :(

**Comment by Fonzee9** [comment]
I still want this fixed... its so annoying

**Comment by gvlfm78** [comment]
Could you provide some video evidence? What I see is not annoying at all if even barely noticeable when payed close attention to
