### ISSUE TITLE
Enchanted golden apples still craftable even when disabled in config

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#62]
They can still be crafted config:
old-golden-apples:
  # This is to change the behaviour / crafting of golden apples to how it was in pre-1.9
  enabled: false
  # If you don't want enchanted golden apples to be craftable, set this to false
  enchanted-golden-apple-crafting: false
  # Enabling this makes the potion effects gained by eating golden apples
  # and enchanted golden apples the same as it was in pre-1.9
  old-potion-effects: true
  # Potion effects golden apples should apply
  # Duration is in ticks (20 ticks = 1 second)
  # Amplifier is potion level -1, so Regeneration IV would be amplifier 3

**Comment by gvlfm78** [comment]
Well your module is disabled, it won't do anything when enabled: is set to false

**Comment by Fonzee9** [comment]
# If you don't want enchanted golden apples to be craftable, set this to false

It is still craftable even when it is set to false.

**Comment by gvlfm78** [comment]
Set enabled to true

**Comment by Fonzee9** [comment]
I did they are still craftable

**Comment by gvlfm78** [comment]
What is your current configuration then.

**Comment by Fonzee9** [comment]
Its on top the first post

**Comment by gvlfm78** [comment]
I said **now** not when we started this conversation. If you followed what I was saying it should be different

**Comment by Fonzee9** [comment]
Its set to false yet its still craftable it should only be craftable if it is set to true

**Comment by gvlfm78** [comment]
**Have you enabled the module by setting _enabled:_ to true**

**Comment by Fonzee9** [comment]
This is to change the behaviour / crafting of golden apples to how it was in pre-1.9

enabled: false

If you don't want enchanted golden apples to be craftable, set this to false

enchanted-golden-apple-crafting: false

**Comment by Fonzee9** [comment]
Notice the If you don't want enchanted golden apples to be craftable, set this to false yet it still craftable

**Comment by gvlfm78** [comment]
`This is to change the behaviour / crafting of golden apples to how it was in pre-1.9`

**`enabled: true`**

`If you don't want enchanted golden apples to be craftable, set this to false`

`enchanted-golden-apple-crafting: false`

**Comment by Fonzee9** [comment]
This is my config still craftable.

  # If you don't want enchanted golden apples to be craftable, set this to false
  enchanted-golden-apple-crafting: false

**Comment by gvlfm78** [comment]
But that is an option of the old golden apple module, so the module itself must be enabled. That means you must also set _enabled:_ to true for it to work

**Comment by Fonzee9** [comment]
This is my config:

https://pastebin.com/2tvzfQaZ

**Comment by gvlfm78** [comment]
Copy paste this over it

https://pastebin.com/bGPHJiaU

**Comment by Fonzee9** [comment]
Thanks :)
