### ISSUE TITLE
Fishing rod knockback glitch into blocks

### ISSUE THREAD

**Issue by BoostedNetwork** [gvlfm78/BukkitOldCombatMechanics#64]
With the Old fishing rod check enabled, people are able to push themselves through blocks glitching themselves out of the map. Basically using the fishing rod knockback to block glitch.

**Comment by gvlfm78** [comment]
What version of the plugin do you have?

**Comment by BoostedNetwork** [comment]
1.4.0

**Comment by gvlfm78** [comment]
But is the person glitching holding the rod too or do you need to players to do this?

**Comment by BoostedNetwork** [comment]
I've only seen it done with two people, and the person being glitched is not holding the fishing rod but taking knockback from the fishing rod.

**Comment by gvlfm78** [comment]
I don't' seem to be able to replicate this bug. Could you provide more information on the exact configuration of blocks that players are glitching through, or even a video?
