### ISSUE TITLE
OldCombatMechanics needs an update for 1.12

### ISSUE THREAD

**Issue by Fonzee9** [gvlfm78/BukkitOldCombatMechanics#65]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre2-released.240317/

**Comment by gvlfm78** [comment]
The plugin shouldn't need an update, it should work anyway. Let us know what doesn't work if you find anything

**Comment by Fonzee9** [comment]
Gives this error on startup and doesn't work: https://pastebin.com/LMkJPfeg

**Comment by Rayzr522** [comment]
@gvlfm78 why are you loading via an InputStream? Why not just use `plugin.getConfig()`?

**Comment by Fonzee9** [comment]
Any update on the 1.12 OldCombatMechanics? I really wanna start my server on 1.12 pre 2 but without this plugin its tough i hate the new pvp. Also the api will stay the same on 1.12 so its worth your time to update.

**Comment by gvlfm78** [comment]
It should work now in test build [#110](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/110/). Please confirm.

**Comment by Fonzee9** [comment]
Yes it works thank you so much :)
