### ISSUE TITLE
1.9 PvP sounds disabled

### ISSUE THREAD

**Issue by ssamjh** [gvlfm78/BukkitOldCombatMechanics#67]
When going on other servers, PVP sounds are disabled somehow.

Mainly when the server is running 1.8.8 with ViaVersion, however it would be a cool feature for this plugin!

**Comment by gvlfm78** [comment]
What exactly do you mean?

What version of the plugin is the server using, and what version of bukkit/spigot?

**Comment by ssamjh** [comment]
Oh hey I'm back.

I'm using version 1.4.1 with Spigot 1.11.2 (built yesterday)

Heres a short video showing the sounds: https://www.youtube.com/watch?v=kVIUQBxASd4

**Comment by Pluginsel** [comment]
I agree.

**Comment by gvlfm78** [comment]
@Pluginsel what version of Bukkit/Spigot & OCM are you running? Does changing anything make the issue go away?

**Comment by Pluginsel** [comment]
What? Tell me more clearly.

**Comment by gvlfm78** [comment]
﻿Ｗｈａｔ  ｖｅｒｓｉｏｎ  ｏｆ  Ｂｕｋｋｉｔ／Ｓｐｉｇｏｔ  ａｎｄ  ＯＣＭ  ａｒｅ  ｙｏｕ  ｒｕｎｎｉｎｇ？

**Comment by gvlfm78** [comment]
OldCombatMechanics

**Comment by Pluginsel** [comment]
Latest. 1.5.0

**Comment by Pluginsel** [comment]
@gvlfm78 When are you going to turn these voices off?

**Comment by gvlfm78** [comment]
What voices?

I still don't understand what the desire here is. Also the video linked no longer works.

**Comment by Pluginsel** [comment]
@gvlfm78 I will share a video.

**Comment by LinsaFTW** [comment]
He means the "Wind" sound when you jitterclick on someone.

I think you cant disable that with a plugin.

**Comment by Rayzr522** [comment]
The sounds are clientside. There’s no way to disable them. You could probably very easily make a resourcepack to get rid of the sound, if it really bothers you that much.
