### ISSUE TITLE
Old HitBox

### ISSUE THREAD

**Issue by Wykaz** [gvlfm78/BukkitOldCombatMechanics#68]
In 1.9+ the hitbox has been reduced you could put them back as in 1.8

**Comment by Rayzr522** [comment]
Are you sure this is true? I've not noticed any difference. Also, this would require manual hit detection and ray-tracing the hits to custom hit boxes. We can't actually change the hit boxes themselves, they're clientside *and* serverside.

**Comment by gvlfm78** [comment]
I could not find anything in the [1.9 changelog](http://minecraft.gamepedia.com/1.9) regarding this. Besides, as Rayzr already outlined, it would be impractical to do so.

**Comment by Wykaz** [comment]
I'm sure there's a change of hitbox to 1.9+. https://www.youtube.com/watch?v=kaXnQaa9vMw&edit=vd
A developer of a large french server made a video and he successfully re-exchange the hitbox as in 1.8. https://www.youtube.com/watch?v=dfGHN93dGVM

**Comment by Wykaz** [comment]
I would like an answer ?
