### ISSUE TITLE
Fishing rod in WG region not counted as PvP

### ISSUE THREAD

**Issue by baticag** [gvlfm78/BukkitOldCombatMechanics#7]
Players can still hit each other with fishing rod in WG protected regions even if in the region PvP is set to false.

**Comment by Rayzr522** [comment]
Sorry for the long response time. The reason they can, is because it's technically not normal PvP; we're applying damage directly to the player in the code, not calling some OnHit event or something like that.

What worlds do you have that require this? Is it possible to just disable it for that world?

**Comment by baticag** [comment]
Thanks for the reply. We can't do it with per world, spawn and pvp area is in the same world since it's SkyPvP gamemode server. Is there a way to hook into worldguard and check if player is in the region with some flag and they cancel or allow damage?

**Comment by Rayzr522** [comment]
We might be able to. It would be nice if we didn't have to hook into it at all, maybe if there was some way to do it in a way that WG recognizes as PvP, but it may come to that. I'll let you know when I figure out what's going to happen with this.

**Comment by gvlfm78** [comment]
We'd have to compile against WorldGuard and check if the player is a worldguard region whose flags have pvp set to false then cancel the event. Not sure if there's another way to do it.

**Comment by baticag** [comment]
Is there anyway to change the way you do this and somehow transfer it to event that is linked with PvP? Since I don't have problem with servers that have WorldGuard, but with other servers that use plugins for PvP restriction

**Comment by Rayzr522** [comment]
That's exactly what I was thinking (having it call some sort of damage event). I believe I can do that, I'd have to do some testing.

**Comment by Rayzr522** [comment]
Ok, so in concept this should work, however in the latest updates they made calling the EntityDamageByEntity event WAY more complicated. I have no idea what these parameters are, something about damage modifiers and functions... so confusing. I'll let you know if I can get it working.

**Comment by Rayzr522** [comment]
Sorry I haven't responded in a while. Here's the problem: I was working on the old armor value module and there are some SERIOUS issues, so I have been at a sort of stand still for the moment. I will try and get everything figured out, but there are some pretty major problems, possibly even API problems that I'm trying to figure out.

I'll try to look into hooking into WorldGuard soon! Thank you for your patience.

**Comment by baticag** [comment]
Yeah I tried dev build and saw that it isn't working. Put it on hold for now, but still think about solving that :)

I tried this one and it's working (I modified it so it uses 1.10), but it's NMS code and I don't know how can you implement it for all versions
https://www.spigotmc.org/resources/knockbackrodrestorer.19990/

**Comment by Rayzr522** [comment]
Interesting. I'll have to look a little more into this, it might do exactly what we need.

**Comment by gvlfm78** [comment]
@baticag Can you try with [this build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/16/)?

I have made the plugin check if other plugins are cancelling the event and therefore not do anything if that is the case. The problem I found, with EssentialsX enabled, is that if you attack a player (out of WorldGuard zones) with a rod faster than every 3 seconds or so EssentialsX will cancel the event. (No idea why). 

You can also enable debug mode and the plugin will tell you what plugins are listening on the event when it was cancelled.
