### ISSUE TITLE
Disable Off-Hand  don't work

### ISSUE THREAD

**Issue by StteveGamer** [gvlfm78/BukkitOldCombatMechanics#70]
Even if you disable the off-hand you can still use. How can I solve this?

**Comment by gvlfm78** [comment]
By having more information on the problem.

**Comment by Rayzr522** [comment]
@gvlfm8 you should probably give *him* more information about what you need to know.

**Comment by StteveGamer** [comment]
@gvlfm78  I'm using spigot 1.11.2 R0.1 SNAPSHOT and the lastest version of your plugin

**Comment by gvlfm78** [comment]
And what does your config.yml look like? (You can insert it using pastebin or similar)

**Comment by StteveGamer** [comment]
[https://pastebin.com/raw/n9TGQJXc](url)

**Comment by StteveGamer** [comment]
https://pastebin.com/raw/n9TGQJXc

**Comment by gvlfm78** [comment]
Can you try turning `whitelist:` under `disable-offhand` to `true`?

**Comment by StteveGamer** [comment]
It works, thank you very much, if you can try to fix it for the next version

**Comment by gvlfm78** [comment]
It will now be the default in the newest OCM version.
