### ISSUE TITLE
Attack timer animation laggy

### ISSUE THREAD

**Issue by Mehuu** [gvlfm78/BukkitOldCombatMechanics#71]
I downloaded OCM to try and recover egg and snowball knockback but wanted to keep the original 1.9+ combat mechanics. But upon changing the config file to match my needs, I discovered that the attack indicator animation was laggy and jumpy.

Pay attention to the indicator under my crosshair and you'll see. (This isn't a resource pack issue, I've have friends playing on default with the same issue.)
[https://youtu.be/itKe3MjEHDU](url)

Even after removing the plugin, reinstalling and changing settings, and using OCMFixer, I still have a jumpy animation. Any solutions? My server is 1.11.2 Spigot and I'm running the latest version of your plugin.

**Comment by gvlfm78** [comment]
Do the items show having any extra NBT tags (especially the sword)? You may need to enable extra item lables with F3 + H (IIRC)

**Comment by Mehuu** [comment]
No extra NBT tags, pulled straight out of my creative inventory.

**Comment by Rayzr522** [comment]
Try this:
- Stop the server
- Inside your main world folder, rename `playerdata` to `playerdata.bak`
- Restart the server

If you're still having problems with the laggy indicator after that, it's not OCM.
