### ISSUE TITLE
NBT error in Attack Cooldown module

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#72]
The server was fine one moment then suddenly there was intense lag and everyone was kicked. Then this error showed up in console: https://pastebin.com/37ZEwsNi . Console isn't responding and no one can log onto it. Also all mcmmo parties were wiped for some reason.

My server is a Spigot 1.10 server.
Plugins: http://prntscr.com/fc5b6n
Server Startup: https://pastebin.com/HtKkkK5V

**There are a ton of issues happening afterwards including:**
- A regular player joined and it welcomed him as if he were a new player. It wiped his inventory and he spawned at spawn.
- Tons of lag
- All mcmmo parties were wiped
- Probably more I will discover eventually

**This error was from OldCombatMechanics plugin:**
 
`25.05 18:35:40 [Server] ERROR gvlfm78.plugin.OldCombatMechanics.module.ModuleAttackCooldown.onPlayerQuit(ModuleAttackCooldown.java:52) `

_Reported by pinkpig on SpigotMC_

**Comment by Rayzr522** [comment]
This would be a bug in Bukkit itself, from what I can tell. The server froze while trying to save the NBT file, which is a CraftBukkit operation. OCM isn't directly touching any files in the attack cooldown module.

**Comment by pinkpig3777** [comment]
Okay thank you.

**Comment by Rayzr522** [comment]
@gvlfm78 do you have any plans to investigate this further?

**Comment by gvlfm78** [comment]
Well I don't really know what we could do about this, it doesn't seem to be a very reproducible or fixable bug, if the responsibility lies within OCM at all.
