### ISSUE TITLE
Blaze Powder Dupe

### ISSUE THREAD

**Issue by T1MOXA** [gvlfm78/BukkitOldCombatMechanics#75]
http://SSMaker.ru/01278e28/
Plugin version 1.4.2
Client 1.11.2
Server 1.11.2

**Comment by gvlfm78** [comment]
Is this the same as #73 ?

**Comment by T1MOXA** [comment]
No, I have a little bit different, I can take from the stand, and each time you open there is a new stack.

**Comment by T1MOXA** [comment]
Is it possible to do without blaze powder ?
Like here - http://ssmaker.ru/55e5e1dd.png

**Comment by gvlfm78** [comment]
In what way are you taking from the stand?

**Comment by T1MOXA** [comment]
Just picked up item from the slot and all...

**Comment by T1MOXA** [comment]
Is it possible to do as I suggested ?

> Like here - http://ssmaker.ru/55e5e1dd.png

**Comment by gvlfm78** [comment]
I managed to make it almost exactly like you showed in test build [166](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/116/)
