### ISSUE TITLE
ModuleShieldCrafting NPE

### ISSUE THREAD

**Issue by NoChanceSD** [gvlfm78/BukkitOldCombatMechanics#77]
Just spamming in console over and over
https://pastebin.com/KHnjgrB6

**Comment by gvlfm78** [comment]
I don't seem to be able to replicate this bug, when exactly does the message appear? What do you do that makes it print in the console?

**Comment by NoChanceSD** [comment]
From the error probably when people go to craft something, i would guess it's when they use the new recipe book stuff in 1.12.

**Comment by pvprangergod** [comment]
hey i found a solution for now, https://www.spigotmc.org/resources/limitcrafting-1-11-updated-disable-crafting-recipes.12962/

enable the crafting in the config and then use this new plugin to block it :)

**Comment by gvlfm78** [comment]
This issue should now be fixed in test build [115](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/115/) and up. Please confirm and report any further bugs

**Comment by NoChanceSD** [comment]
Seems good to me so far
