### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to OldCombatMechanics v1.4.2

### ISSUE THREAD

**Issue by DefinePvP** [gvlfm78/BukkitOldCombatMechanics#85]
https://pastebin.com/VSV9bpwY

I am running 1.12 on the latest version of PaperSpigot.  I have tried Spigot also, and the same errors occur.

**Comment by gvlfm78** [comment]
Duplicate of #77 

I'm going to release the update now with all of the bugfixes
