### ISSUE TITLE
Dynamic Feature Toggle

### ISSUE THREAD

**Issue by BurnyDaKath** [gvlfm78/BukkitOldCombatMechanics#86]
Hey, I have a minigame server, and I want to load/unload this plugin based on player votes (player wanting next match to be 1.8 or 1.9). However, if I would just disable the plugin, not every feature of this plugin will disable (for example, modules based on player joining). Is there any way to properly unload this plugin? If not, adding this feature would be great.

**Comment by Rayzr522** [comment]
Another way to handle this would be to add in-game configuration commands to OCM, then you could just use those to toggle features on and off.

**Comment by Rayzr522** [comment]
I'm pretty sure almost all systems are fully compatible with dynamic loading and unloading at this point, so I'm closing this issue.
