### ISSUE TITLE
Shield drops if killed when sword blocking

### ISSUE THREAD

**Issue by BurnyDaKath** [gvlfm78/BukkitOldCombatMechanics#88]
If player sword blocks and someone kills him, the shield will be dropped. The problem is supposedly with ModuleSwordBlocking using `is.getType().equals(Material.SHIELD)` instead of `is.getItemStack().getType().equals(Material.SHIELD)` in onItemDrop method, which tries to compare EntityType with Material.

**Comment by Rayzr522** [comment]
@gvlfm78 TL;DR You should use `==`.

Using `.equals` is both unnecessary *and* it indirectly caused this. Since `.equals` takes an `Object` as the parameter, your IDE didn't realize you were comparing two different enums.

**Comment by BurnyDaKath** [comment]
IntelliJ told me straight away that the problem is in comparing 2 different enums...

**Comment by gvlfm78** [comment]
I had actually researched == vs .equals for enums in Java and ended up on [this](https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals) StackOverflow page but I did not then have time to go around switching up all of the pre-existing statements.

About the IDE: I have actually several times tried switching to IntelliJ, but every time I found something that just didn't work for me, such as it doing things I never asked it to do, or make the formatting go all over the place, apart from not being able to have more than one project open at once in the same screen.

I will proceed to fix this issue, and when I have time convert pre-existing .equals checks for enums to ==.

**Comment by Rayzr522** [comment]
I would be glad to do that for you, but I just want to say that you *can* have more than one IntelliJ project open at once. It's a daunting tool at first, but my productivity has gone up easily 50% since I started using it.

**Comment by gvlfm78** [comment]
I do recognise that it has many useful features to increase productivity, that is why I have tried to switch to it many times. I will give it another try now but from what I understand there isn't a 'proper' way of having more than one project open at once in the same window.

**Comment by Rayzr522** [comment]
In the same window? I'm not sure if that's possible, although you might be able to achieve that by opening the folder *containing* the projects. I'll have to try it out. If you have any questions about how to do certain tasks with IntelliJ just let me know, you know where to contact me.

But back on topic, would you like me to go through and fix as many `.equals` as possible?

**Comment by gvlfm78** [comment]
Yes please. I was going to have a look at some other issues such as mcmmo compatibility.

In the meantime I have changed the one relevant to this issue, so it should now be fixed for [test build 124](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/124/) and above.
