### ISSUE TITLE
Weird error every minute

### ISSUE THREAD

**Issue by BytedByte** [gvlfm78/BukkitOldCombatMechanics#89]
Hi, This error keeps popping up literally once every minute. I've tried reinstalling plugin and gotten rid of config. Still happens, any idea why? http://i.imgur.com/IqqxlGU.png

**Comment by Rayzr522** [comment]
Already reported in #76 ([my comment](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/76#issuecomment-311675410)).

**Comment by gvlfm78** [comment]
Please comment on #76 with extra information to allow us to fix the issue
