### ISSUE TITLE
MobArena Incompatible

### ISSUE THREAD

**Issue by aycgit** [gvlfm78/BukkitOldCombatMechanics#9]
the plugin is not mobarena compataible, if u join a arena u get sword which tell u they have 1000 attack speed but they just work as 1.9 combat (on a 1.10 server) 

no errors, just the above

**Comment by aycgit** [comment]
this only happens time to time (sometimes)

**Comment by gvlfm78** [comment]
I just tested this and I'm unable to replicate this. Does it happen with specific classes?

**Comment by aycgit** [comment]
im testing it right now but it only happens sometimes

**Comment by aycgit** [comment]
give me a sec

**Comment by aycgit** [comment]
when it happened it was knight class

**Comment by Rayzr522** [comment]
That is quite odd. Have you modified the Knight class at all? I have MobArena on my server along with OldCombatMechanics, and it works fine.

**Comment by aycgit** [comment]
@Rayzr522 i just installed mobarena with the default class knight

**Comment by Rayzr522** [comment]
Hmmm. Try rebooting? :P

But seriously, try restarting your server. You never know

**Comment by aycgit** [comment]
it doesnt seem to happen anymore now, i will message here if it happens again

**Comment by Rayzr522** [comment]
Alright

**Comment by aycgit** [comment]
doesnt happen anymore for me, could be lag but i just wanted to report it :)
