### ISSUE TITLE
MCMMO Serrated Strikes right click ability

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#94]
MCMMO right click ability doesn't work with sword blocking module enabled

**Comment by Ac3dUd3** [comment]
On my factions server, when using 1.9 - 1.12 client and right clicking with your sword, a shield appear in your offhand which makes McMMO ability "Serrated Strikes" unable to activate.

**Comment by Ac3dUd3** [comment]
Using protocolsupport plugin for the multi version client support. Not sure if that helps or not

**Comment by gvlfm78** [comment]
Thank you for the information. What version of the plugin are you using?

**Comment by Ac3dUd3** [comment]
1.5.0

**Comment by Ac3dUd3** [comment]
Mcmmo. Is 1.5.08

**Comment by gvlfm78** [comment]
I have tried testing this and managed to get "Serrated Strikes" to work. I am using OCM 1.5.1 and the latest McMMO from [here](https://ci.drtshock.net/job/mcMMO/).

Can you upload a copy of your OCM config.yml to pastebin or similar service?

Could you provide more detail on what exact part of the ability doesn't work? Do you get the "ability activated" message but it then doesn't do anything?

**Comment by Ac3dUd3** [comment]
the bug was given to me by a player on my network, i have no done extensive testing.
"Right clicking a sword will make a shield appear in your off-hand slot making 'Serrated Strikes' (McMMO) impossible"
This is the OCM config, perhaps there is a setting i need to change?
https://hastebin.com/kenanenili.bash

**Comment by Ac3dUd3** [comment]
perhaps its protocolsupport blocking it?

**Comment by ridalarry** [comment]
@gvlfm78 Anything new about this issue?

**Comment by gvlfm78** [comment]
I told you, serrated strikes works perfectly fine for me, so until someone documents a way in which it doesn't work I can't do anything, as I'd have no clue what the problem is

**Comment by RainOfPain125** [comment]
sword-blocking:
  # This is to allow players to block with swords again by getting a shield while they hold right click with a sword
  enabled: false

With this set to false, no shields pop up (of course) and this allows me to activate Serrated Strikes

https://www.youtube.com/watch?v=fw-QpMfs0wA&index=1&list=PL625Ue11DsARyZIrTHCsSL5Y0_xe65ebC

https://www.youtube.com/playlist?list=PL625Ue11DsARyZIrTHCsSL5Y0_xe65ebC

In both videos I'm just right clicking

**Comment by gvlfm78** [comment]
What happens if you shift + right click?

**Comment by KuraiKokoro** [comment]
At the moment when shields are enabled, the only way to activate serrated strikes is through shift right clicking rather than just right clicking.

**Comment by gvlfm78** [comment]
@KuraiKokoro Does that also happen when you're holding a shield in a server without OCM? i.e. is holding the shield the problem?

**Comment by KuraiKokoro** [comment]
Just went ahead and disabled OCM, holding the shield is the problem.

**Comment by RainOfPain125** [comment]
I just gave up trying to use OCM due to the two major bugs we were having with it. .-.

**Comment by gvlfm78** [comment]
@Ac3dUd3 @ridalarry @RainOfPain125 @KuraiKokoro To clarify, on a normal 1.9+ server with just McMMO, is this still an issue when using shields in a normal manner?
