### ISSUE TITLE
Unable to move chestplate with elytra module enabled

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#95]

**Comment by Disorbs** [comment]
Hello I'm unable to move my chest plate or anything for that slot when the module is enabled such as

disable-elytra:
  enabled: true
  worlds: [pvp]

Now Elytra is disabled in PVP world good BUT when a player in the pvp world wants to change out a chest plate when fighting or just by standing in the world he can't remove the chest plate once placed.

1. Enable module for the world.
2. Go to that world and wear a chest armor and try to remove it.
3. It won't work.

**Comment by gvlfm78** [comment]
This _should_ now be fixed in test build [130](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/130/). Please confirm and report any other bugs.
