### ISSUE TITLE
Can use enderpearl infinitely if renamed

### ISSUE THREAD

**Issue by gvlfm78** [gvlfm78/BukkitOldCombatMechanics#96]

**Comment by Disorbs** [comment]
Infinite Pearl glitch when module is enabled and the item is renamed in an anvil.

disable-enderpearl-cooldown:
    enabled: true
    worlds: []

1. Get a ender pearl and rename it to something random "rkrm3r"
2. Toss it and it wont remove itself once thrown.

**Comment by gvlfm78** [comment]
This issue should now be fixed in test build [#129](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/129/). Please confirm. 

This also fixes the issue where having multiple stacks of enderpearls in your inventory consumes the first one even if it isn't the selected one.
