### ISSUE TITLE
InventoryClickEvent error in elytra module

### ISSUE THREAD

**Issue by DuckCraftPvP** [gvlfm78/BukkitOldCombatMechanics#98]
https://hastebin.com/gerupikiji.vbs

**Comment by Rayzr522** [comment]
- What version of Bukkit/Spigot are you running on?
- What version of OldCombatMechanics are you using?

**Comment by DuckCraftPvP** [comment]
1.12 for paper spigot
and oldcombatmechanics is 1.5.0

**Comment by Rayzr522** [comment]
@gvlfm78 is this what you fixed in #95?

**Comment by DuckCraftPvP** [comment]
No its not, That happens when u click anywere when u have inventory open but still allows you to move stuff. That one is where he could not move items in said inventory.

**Comment by gvlfm78** [comment]
Please try the [latest test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/130/), I have been making some changes to the elytra module trying to fix #95  and so this could have been fixed too.

**Comment by DuckCraftPvP** [comment]
works thank you
