### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DuckCraftPvP** [gvlfm78/BukkitOldCombatMechanics#99]
https://hastebin.com/decehakabe.vbs

**Comment by gvlfm78** [comment]
Is this not the same at issue #98? I might have forgotten to release the update with the fix

**Comment by DuckCraftPvP** [comment]
i dont think so but might be.,

**Comment by gvlfm78** [comment]
Please try the [latest test build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/) to check if the issue is still present
